### ISSUE TITLE
Add production rooms to onboarding UI

### ISSUE THREAD

**Issue by rabble** [planetary-social/planetary-ios#1004]
We built the UI, let's ship it with civic.love and planetary.name.

**Comment by Chardot** [comment]
@rabble Is this list going to contain the migrated pubs into Rooms/Hubs?

**Comment by mplorentz** [comment]
We are calling this blocked by #941, because we don't want to have tons of people registering aliases before they can log into the room server to manage/delete aliases.

**Comment by mplorentz** [comment]
@cooldracula @rabble the info I need for each hub server we want to show during onboarding is:
1. Name
2. Icon (probably Planetary logo for starters?)
3. Multiserver address (domain name, port, public ed25519 key)
4. secret "magic token" that acts as an invite that can be redeemed multiple times.

If you could pass along the details when the server(s) are up I will get this done!
