### ISSUE TITLE
Wire up migration UI to scuttlego bindings

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/planetary-ios#1007]
We need to add design and write functions in scuttlego to start the go-ssb -> scuttlego migration. We also need to call these functions from swift and wire them up to the migration UI (#1006).

[Figma](https://u3302489.ct.sendgrid.net/ls/click?upn=5jn-2BNVr6mWrJbcZ1z4kro3nySutAgQPt34lNFAjvKx1CW5gTp3QTTK89efGFMP2iXCshbbOaiR24-2BhbBw7WUBEPSSr5jp2ENb3zyIlWEUsbfew0WIk01qos-2FPnL0gieyoXfOXLd6zvcHudolX8of8lHjnXwzu5s-2FYqjEpPSa7Jg-3DUpDa_lXN3p3eURwelP0H6-2F02Tv0p5JhEfFVPl3eH6yeg8rJjabLK8wYNkBa9BGnyIXjj6Xum5u-2FzZrHrLknfJamz4yK2TEgTYHcC9FFY-2Brz1mTwBMW2684QnkLfP1GggUYXW0rzhkorQ2D9uTJcGWwpY04vMzd9azrscBNjBK3OSL86Mg3i51sAbk2jADh3ONVcS50NATvOYNX6ilf-2Bly19054p3oFRvD8JceWGRtKOcYKApBZAl1ltDhvACGdHNhKO-2F3)

**Comment by mplorentz** [comment]
@boreq do you want a separate ticket for this in the scuttlego project?

**Comment by boreq** [comment]
>do you want a separate ticket for this in the scuttlego project?

I will probably create a technical task specifically for scuttlego once we know how to solve this from a technical standpoint @mplorentz. For now let me describe what the problem that we are trying to solve is.

Under normal circumstances scuttlego is initialized when `ssbBotInit` is called. This function is either called after going through a certain step of onboarding or when launching the app with your identity already created. `ssbBotInit` accepts configuration which is needed to start running scuttlego and this configuration is also needed to run the migrations.

Internally scuttlego has a list of migrations that need to be executed. For now this list only has one migration in it. In the future it is very likely we will have other migrations in that list e.g. database migrations changing the schema of the database used by scuttlego. Migrations are executed one by one. Migrations are capable of periodically persisting state so if they get interrupted or fail they don't have to start over. If a particular migration was already successfuly completed in the past then obviously it won't be run. 

Coming back to the bindings: in function `ssbBotInit` we call a function called `Run` which runs the entire stack eg. starts the networking stack etc. Our goal here is that we need to somehow run a function called `RunMigrations` before running that `Run` function. Function `RunMigrations` must be called before `Run`. Function `RunMigrations` needs to be executed while displaying some kind of a screen to the user.

I could see this done in two ways:
- make `ssbBotInit` block and while it is running display the migration screen, give it a callback to call to update data on it (some kind of a progress bar for example)
- create a separate function such as `ssbBotRunMigrations` and make sure it is always called beforehand, this has a disadvantage that this also needs the same config and in general seems more complicated as we NEED to ensure that it gets called first (I could make sure that that is the case in the Go code to prevent bugs)

Additional info: the migrations obviously also need to be called when the app wakes up in the background to get new data without user intervention.

Here is how I imagine the screen could look like:

![Image](https://user-images.githubusercontent.com/1935975/208111621-74b684b8-a02f-40fd-ba49-fa8bbbd97652.png)

The following values that I could easily generate would be needed to display that screen:
- the total number of migrations (an integer)
- the index of the current migration being run (an integer)
- the progress of the currently executed migration (a float between 0 and 1)

**Comment by mplorentz** [comment]
@boreq thanks for the thorough writeup. I think this option will work for us:
> make ssbBotInit block and while it is running display the migration screen, give it a callback to call to update data on it (some kind of a progress bar for example)

I'll defer to @Chardot on the progress bar design. But I do think the Discord design seems to walk a good line between engineering effort and user experience. 

Let's make sure we have room in the process for error messages/handling. Maybe we should modify the signature of `ssbBotInit` so that instead of returning a bool it returns `null` on success and some kind of error information (Int, String, Struct, JSON?) on failure.

**Comment by boreq** [comment]
>What is the range of time to run this Scuttlego migration? Are we talking about minutes, hours, or days?

With very preliminary optimizations a large database (such as Rabble's) imports in around 8 minutes. An average database would probably take below 4 minutes.

I have not fully optimized this process yet so the amount of time needed to import a database will be lower in the future. Only this morning Rabble's database took 20 minutes to import. I am making some notes here https://github.com/planetary-social/planetary-ios/issues/1023 but they are mainly for myself so it is hard to decipher them without asking me :confused:.

I want to aim for an average import to take around 2 minutes.

>E.g will large databases take longer?

The time needed to import a database scales linearly with the number of messages in the database. 

>Tech Question: Can the migration run a storage needs check before attempting the migration?

No, it is too complicated.

**Comment by mplorentz** [comment]
> Tech Question: Can the migration run a storage needs check before attempting the migration?

@boreq I think we shoudl do some sort of best effort guess, because filling up the disk is not easy to recover from. We could do something like show a warning message if you have less free disk space than your old db is taking up. We could do a check like that from the Swift side.

**Comment by boreq** [comment]
> @boreq I think we shoudl do some sort of best effort guess, because filling up the disk is not easy to recover from. We could do something like show a warning message if you have less free disk space than your old db is taking up. We could do a check like that from the Swift side.

If we want to make something like this then I would prefer to be able to display some warnings/notifications from Go so that I can display warnings for other migrations as well.

**Comment by danlatorre** [comment]
![Image](https://user-images.githubusercontent.com/627234/212434701-fdfe79cc-f067-4b2b-9712-416ae9b449e5.png)

**Comment by boreq** [comment]
Feedback: is the button needed? It feels like a redundant action. Shouldn't the screen disappear automatically?

**Comment by danlatorre** [comment]
People may do other things and come back. We don't know. Either way the button is for a core usability principle:

#1: Visibility of system status

The design should always keep users informed about what is going on, through appropriate feedback within a reasonable amount of time.

This part of how UX can convey trust. 

https://www.nngroup.com/articles/ten-usability-heuristics/

**Comment by Chardot** [comment]
I polished some details on the screen:

![Image](https://user-images.githubusercontent.com/477835/212692287-4944ff77-07e6-47de-bb19-40403208cf5e.png)

Also here's a [clickable demo](https://www.figma.com/proto/6oTsbY3vHME19RNtgSGdAw/Planetary-Design-Plan?page-id=3969%3A33073&node-id=3969%3A33157&viewport=898%2C654%2C1&scaling=min-zoom&starting-point-node-id=3969%3A33074) (Click to browse, press R to restart):

**Comment by boreq** [comment]
We agreed to something along the lines of:

```
ssbInit(old stuff..., migrationCallback(...))

func migrationCallback(lastPercentDone: Float, state: Int, migrationIndex: Int, numberOfMigrations: Int, errorCode: Int)
```

**Comment by mplorentz** [comment]
And to clarify, per the product team's decision, we won't be using the `lastPercentDone` parameter for this migration. We are just making space for that in the future.

**Comment by mplorentz** [comment]
yeah I guess it is. Let's do that then.

**Comment by boreq** [comment]
I also did this so we can remove the old code for the previous migration I guess:
- https://github.com/planetary-social/scuttlego/issues/155

**Comment by boreq** [comment]
@mplorentz can you tell me why this is blocked?

**Comment by mplorentz** [comment]
I think I marked it blocked because I couldn't merge it to `main` until #1118 was fixed. It looks like that is done now though. Assigning this back to @martindsq and To Do.

**Comment by mplorentz** [comment]
#1141 has been merged. Closing!
