### ISSUE TITLE
scuttlego bindings: implement ssbFeedBlock

### ISSUE THREAD

**Issue by boreq** [planetary-social/planetary-ios#1008]
As far as I can tell we need to change the way the ban list is handled:
- the functions to remove/add stuff to the ban list should accept hashes and not actual refs
- the functions to remove/add stuff to the ban list should always be called whenever the ban list changes, they shouldn't be called just for things which are in sqlite - that way scuttlego can preemptively prevent things from being replicated

To do:
- [x] add functions modifying the ban list https://github.com/planetary-social/planetary-ios/pull/1109
- [ ] use those functions in Swift

**Comment by boreq** [comment]
This ticket is the one that is most closely related I think:
- https://github.com/planetary-social/scuttlego/issues/172

I don't know for sure if the other one has the same cause yet.

**Comment by boreq** [comment]
> I wrote the code to use these functions in Swift. After testing them I got this error and replication got stuck, so I wasn't able to verify that it works correctly:
> 
> ```
> evel=error ts="2023-01-19 15:48:45.4168740 (UTC)" source=golang err="could not get contacts: could not get fresh data: transaction failed: could not get wanted feeds: could not get feed state: could not get a feed: loading failed: failed to get the message: message not found: Key not found" name=gossb.manager message="send feed to replicate failed"
> ```
> 
> I think @boreq is tracking work towards fixing this in [planetary-social/scuttlego#168](https://github.com/planetary-social/scuttlego/issues/168) maybe? If I'm wrong please link the correct ticket.

This was fixed here most likely:
- https://github.com/planetary-social/scuttlego/pull/175

**Comment by boreq** [comment]
I believe that we still have to change some Swift code here so that we always call `ssbBanListAdd` / `ssbBanListRemove` whenever something is added or removed from the ban list. We also need to change the code so that it passes a hash to those functions and not the id it tried to get from sqlite as those are present only for data which we have in the db already.

**Comment by boreq** [comment]
Not sure why this is blocked, moving it out of that column.

**Comment by mplorentz** [comment]
@martindsq assigning this to you. I think the remaining work here is something like:
- check out the `use-new-ban-api` and merge the latest changes from `scuttlego-migration-ui` and `project-raptor` into it
- Test that that ban API is working by:
    - copying the planetaryCloudAPISecret from Secrets.release.plist to Secrets.debug.plist
    - Try banning an account and message on the test network following our [process](https://github.com/planetary-social/infrastructure/wiki/Banning-Content) and make sure that they are deleted from your device.
    - delete the planetaryCloudAPISecret from Secrets.debug.plist before you commit anything
    - merge this into `scuttlego-migration-ui` or `project-raptor`.

I don't think this should block the internal TestFlight release.

**Comment by boreq** [comment]
The new implementation just has one function `ssbSetBanList` and the logic in swift was simplified.
