### ISSUE TITLE
Fix mark as read in notifications tab

### ISSUE THREAD

**Issue by rabble** [planetary-social/planetary-ios#1013]
The mark as read button provides no visual feedback when pressed and doesn't reset the number on the notifications tab icon. This is a bug. 
![Screenshot 2022-12-07 at 2 37 17 PM](https://user-images.githubusercontent.com/76/206066567-3501a11f-0646-454e-b7c0-c5bac8e12529.png)

**Comment by martindsq** [comment]
Try again after merging #1240
