### ISSUE TITLE
All hashtags say "no posts here yet"

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/planetary-ios#1021]
Steps to reproduce:
1. Launch the production version of Planetary (1.3.11)
2. Open the hashtags tab
3. Tap any hashtag with a number greater than 0 next to it.
Expected: That number of posts are shown
Actual: No posts are shown

**Comment by boreq** [comment]
Wasn't this fixed @martindsq?

**Comment by martindsq** [comment]
This was fixed. Probably made a mistake in the github project.
