### ISSUE TITLE
Check if scuttlego builds have that identity loading bug fixed

### ISSUE THREAD

**Issue by boreq** [planetary-social/planetary-ios#1028]

**Comment by boreq** [comment]
The bug was fixed here. https://github.com/planetary-social/planetary-ios/commit/15b175aaf42d326bc7b75825fec82d660f2f817b
 there is a similar entry here https://github.com/planetary-social/planetary-ios/blob/project-raptor/Resources/FBTT.entitlements

**Comment by boreq** [comment]
Ok, there is something wrong even when running on iphones and simulator. I am being asked to go through onboarding every time. Perhaps this is a problem with the separate version of the app that we created for scuttlego. We had to change a lot of strings in various config for this and maybe we got one of them wrong.

**Comment by mplorentz** [comment]
I think we need to change the keychain access group in the scuttlego branch to the scuttlego bundle ID, similar to what @martindsq did [here](https://github.com/planetary-social/planetary-ios/pull/990/files) for the main branch.

**Comment by boreq** [comment]
This seems to be fixed now.
