### ISSUE TITLE
Hidden Tab Bar Icons

### ISSUE THREAD

**Issue by lincolnanders5** [planetary-social/planetary-ios#106]
This happens randomly, but the bottom icons will disappear. Here, the Notifications tab shows all the time. Switching to Light Mode makes all the other tabs show up, but hides the Notifications icon.

![image](https://user-images.githubusercontent.com/11580685/81488572-88d97d00-9238-11ea-95d7-4ae216f01bd3.jpeg)
![image](https://user-images.githubusercontent.com/11580685/81488588-b6262b00-9238-11ea-8248-6afa637aa3ea.jpeg)
![image](https://user-images.githubusercontent.com/11580685/81488591-b9211b80-9238-11ea-8d70-59c1a991a831.jpeg)
![image](https://user-images.githubusercontent.com/11580685/81488593-bde5cf80-9238-11ea-9f48-203d97c8927d.jpeg)
![image](https://user-images.githubusercontent.com/11580685/81488594-c0e0c000-9238-11ea-8500-86560fb88dd8.jpeg)
![image](https://user-images.githubusercontent.com/11580685/81488618-14eba480-9239-11ea-87ef-48dc2075e4b6.jpeg)

**Comment by rabble** [comment]
@lincolnanders5 we've got a fix for this in the works for the next release. Thanks for pointing it out.

**Comment by lincolnanders5** [comment]
Still seeing this issue in 0.9.23 😓
