### ISSUE TITLE
Rewrite Thread/Replies view in SwiftUI

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/planetary-ios#1062]
We have updated many of our message cells to use SwiftUI, but if you tap on a message to view replies we still show the old UIKit view.
<img src="https://user-images.githubusercontent.com/1165004/209190983-63aa7262-c466-40ce-9942-adf2ad97cf63.jpeg" width="300" />

**Comment by boreq** [comment]
Related #1198?
