### ISSUE TITLE
Reply to reply not rendered correctly

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/planetary-ios#1100]
Steps to reproduce:
1. Find a reply that has replies on the profile screen (this message is one: `%dzpWLnEY0a5At836ujGnVMHfQKGfVmA4TsvZ1wC06N4=.sha256`)
2. Tap on the post 
Expected: The reply is opened and replies to it are displayed
Actual: The root post is displayed.

**Comment by martindsq** [comment]
Try again after #1062
