### ISSUE TITLE
Add proper line spacing to markdown formatting

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/planetary-ios#1111]
We aren't giving proper space to headings and text blocks in our markdown I think. Here's are screenshots of the same markdown rendered by the popular static site generator Jekyll, and Planetary. Notice how easy the first is to scan vs. Planetary:

![Image](https://user-images.githubusercontent.com/1165004/213474321-a0294066-c174-42e0-aea3-877fc83949c5.png)

![Image](https://user-images.githubusercontent.com/1165004/213474199-efc78f1f-042f-4483-8146-48ec1ae9c93d.png)

The ID of the SSB post is `%4S+HCaE039AMopRiB06aPOVJ3vhlpagU9maxOlxhgkw=.sha256`

**Comment by boreq** [comment]
Dupe #198?
