### ISSUE TITLE
Incorrect formatting when replying to a reply

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/planetary-ios#1127]
It looks like when we reply to replies we are setting the `root` and `branch` parameters to the same message, when really the `branch` should point to the reply we are replying to. An example of this can be seen in `%WSlEhsYZZpZbDnvC92AgwOmFF7Ou7DgPJBgAFzEtyjA=.sha256` as reported by @mixmix in `%0dum9qqxUi8uBGpFlMrDfmH4WaJWpZ4GttsmtiufDnY=.sha256`.

**Comment by mixmix** [comment]
I opened a detailed issues on manyverse that I closed because it didn't look to be manyverse. 

https://gitlab.com/staltz/manyverse/-/issues/2168

Hit me up if you need help figuring out what branch should be. It's the original tangle!

**Comment by mixmix** [comment]
I think you need to get away from the concept of "reply" here.
`branch` is used when "speaking into a thread" and indicates the context into which you're speaking... i.e. I've seen A,B,C,D

it is replying to that _context_, not a specific message

Forks are used to estabilish a new sub-context
