### ISSUE TITLE
Scuttlego erasing lots of messages

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/planetary-ios#1139]
I migrated my main profile to scuttlego the other day and it seemed to be erasing a lot of messages from Badger. 

I'm not sure if these steps will reproduce the issue but here are the rough steps I took before it happened:
1. Install the `scuttlego-migration-ui` branch on top of my main Planetary installation.
2. Encountered #1118.
3. Deleted Planetary.
4. Reinstalled the `scuttlego-migration-ui` branch.
5. Watched it replicate message until I had about 300k in Badger as reported by `ssbRepoStats()` in the Debug menu -> GoBot -> Messages in Badger.
6. Kept watching the number of message in Badger going down 5k-10k messages every minute or so. Eventually it got down to ~230k messages so I deleted the app and reinstalled the ASV.

[821E00FA-9C37-4483-872E-F7B679FF9B60.zip](https://github.com/planetary-social/planetary-ios/files/10690240/821E00FA-9C37-4483-872E-F7B679FF9B60.zip)

**Comment by mplorentz** [comment]
I'm mostly just opening this to communicate it to @boreq so he is aware. I'm not sure if this is very actionable. Maybe we should wait and see if it happens again before putting time towards it.

**Comment by boreq** [comment]
Could be related to this pull request:
- https://github.com/planetary-social/scuttlego/pull/175

Because of all the branches I lost track of which fixes were added to which branch.

**Comment by mplorentz** [comment]
I haven't seen this again and neither has anyone else. Closing because we don't have enough data for this to be actionable.
