### ISSUE TITLE
repoStats is called innecessarily when calling updateReceive

### ISSUE THREAD

**Issue by martindsq** [planetary-social/planetary-ios#1142]
On each refresh/sync cycle, the code calls needsViewFill that computes the number of messages in the sqlite database and the number of messages in the repo. The number of messages in the repo is just used for printing the result to the log and not used functionally in the app. This increases code complexity and lower the readability.

Solution: Get rid of needsViewFill, and reuse the code inside to compute the largest sequence number in the database.

**Comment by boreq** [comment]
Also the number of messages can go down so the current logic which errors out if that happens is wrong.

When the number of messages can go down:
- migration fails to migrate all messages
- migration migrates all messages but some of them were nulled so they were ignored
- a feed is banned and removed from the database
- a feed falls out of the social graph (not yet implemented)
