### ISSUE TITLE
Crash when trying to edit draft

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/planetary-ios#1147]
My copy of Planetary is crashing whenever I try to edit a post I was composing. Steps to reproduce:
1. Type the text shown in the screnshot
2. Close the new post screen
3. Open the new post screen again.

The app crashes. [Bugsnag](https://app.bugsnag.com/verse/planetary/errors/63e6d1048a126700080f6089?filters[event.since]=30d&filters[error.status]=open)

![Image](https://user-images.githubusercontent.com/1165004/218221705-3ba42369-ec1a-4ab4-8580-0e5a5a00c388.png)

**Comment by martindsq** [comment]
Closed this as [completed](https://github.com/planetary-social/planetary-ios/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3Acompleted) in https://github.com/planetary-social/planetary-ios/pull/1261
