### ISSUE TITLE
Show a better description when triggering the forked feed protection

### ISSUE THREAD

**Issue by martindsq** [planetary-social/planetary-ios#1162]
Right now we display an alert saying

> Planetary is currently restoring your data from the network, and cannot publish new posts at this time.

We should show more information, like, what happened, and how to reset the forked feed protection (directions to the debug menu maybe).

**Comment by mplorentz** [comment]
I agree. Probably there should even be button on the alert that lets you reset forked feed protection with plenty of warning and a confirmation dialog.
