### ISSUE TITLE
"Blobs gone" from the latest release

### ISSUE THREAD

**Issue by boreq** [planetary-social/planetary-ios#1192]
Blobs don't seem to be showing up.

Findings:
- `GoSbot/blobs` contains 1287 files which seem to be valid images
- the blobs which are not loading in the screenshot (from the help message) are in there
- perhaps a Swift bug?

Screenshot of the problem:
![img_2942](https://user-images.githubusercontent.com/1935975/220906110-ccc9e1bb-eba2-4b03-9b1e-93f86c4df7bd.png)

**Comment by boreq** [comment]
Is this still a problem @danlatorre? I didn't fix this and I don't know what could have caused this as all those blobs are on your phone.

**Comment by danlatorre** [comment]
I think we can close this. Not sure the of the source issue since a new release loaded and resetting forked feed protection resolved it.

**Comment by boreq** [comment]
Resetting forked feed protection is most likely not related to this problem.

**Comment by boreq** [comment]
Closing as it is unclear what is happening and if this is still a problem, will reopen if we see this again.

**Comment by mplorentz** [comment]
I saw this again yesterday and again today. Here are [logs](https://github.com/planetary-social/planetary-ios/files/10851655/C1E02479-6B99-44D2-B17B-663BEA4DDF54.zip), I can provide a db as well although I doubt it will help as I'm pretty sure all the blobs are there on disk they just aren't loading for some reason.

**Comment by boreq** [comment]
Yeah I checked that all the blobs are there. I think it is some kind of a swift-related bug or maybe the files get locked or something. I will try to replicate this somehow. Weird thing that happened to me today is that I opened the app and it said "your feed is empty" and didn't display any messages until I restarted it.
