### ISSUE TITLE
No replication happening

### ISSUE THREAD

**Issue by boreq** [planetary-social/planetary-ios#1195]
This is a problem for @mplorentz. @martindsq has a similar problem where the replication isn't happening for some of his followees.

**Comment by boreq** [comment]
Maybe fixed in:
- https://github.com/planetary-social/scuttlego/pull/226

**Comment by boreq** [comment]
Released in TestFlight 406 and it caused me to get more messages.

**Comment by mplorentz** [comment]
My badger db message count is going up now, but SQLite isn't getting any new messages for me. Do you want logs or a fresh db export? And would you like a new ticket or to reopen this one?

**Comment by boreq** [comment]
@mplorentz new export would help because I definitely fixed the fact that your social graph was being generated incorrectly from db data but there must be still something wrong there then.

**Comment by boreq** [comment]
Findings:
- the fix for this is here https://github.com/ssbc/epidemic-broadcast-trees/commit/8d1d2db51093bc3b17adec93e2b4232894486409

**Comment by boreq** [comment]
Not the same bug as @martindsq was experiencing. @martindsq was experiencing https://github.com/planetary-social/scuttlego/issues/172. Perhaps @mplorentz it experiencing a problem with user defaults?

**Comment by boreq** [comment]
I am going to close this since we determined that:
- Matt was most likely facing now fixed: https://github.com/planetary-social/scuttlego/pull/206
- Martin was facing: https://github.com/planetary-social/scuttlego/issues/172
