### ISSUE TITLE
Initial list of posts is displayed oldest-first

### ISSUE THREAD

**Issue by tanuva** [planetary-social/planetary-ios#194]
It seems like the initial list of posts that is shown directly after onboarding is displayed with the oldest post first. It would probably be nicer to have the newest post first, wouldn't it? 😊

**Comment by martindsq** [comment]
Yes, you are right! Initial list of posts are preloaded from a JSON file when the app is installed. We recently changed from sorting posts by date to sorting by id which is a faster query. The list of preloaded posts should be reversed so the latest post matches the highest id.

**Comment by rabble** [comment]
@tanuva for new users we can flip that around in our import script, definitely worth doing
