### ISSUE TITLE
bearer token service broken

### ISSUE THREAD

**Issue by rabble** [planetary-social/planetary-ios#211]
the pubs need to be providing the bearer tokens to the cloud functions and when we switched from go pubs to js pubs that stopped happening. this should be fixed.

**Comment by martindsq** [comment]
@boreq can we close this issue?

**Comment by boreq** [comment]
I am unsure as this talks about the cloud functions and pubs and not about the in-app implementation. When it comes to the in-app implementation: go-ssb had some code for this but the code was unused and scuttlego doesn't support this system at all. My current understanding is that indeed we run normal stock JS pubs which means that they don't provide this mechanism. I don't know what we need those tokens for though. I think it is a question to @rabble / @mplorentz.

**Comment by mplorentz** [comment]
We can close this. We are using a oauth-ish setup to get bearer tokens via a google cloud function. We use them to fetch the ban list and it's working ok.

**Comment by mplorentz** [comment]
The idea of pubs issuing bearer-tokens was cooler though.
