### ISSUE TITLE
Onboarding Enhancement: Allow users to opt in or out of bug report tracking during onboarding

### ISSUE THREAD

**Issue by rabble** [planetary-social/planetary-ios#218]
~~On the last step of on boarding the layout isn't right, some text is cut off.~~ This is no longer an issue. 

Also while you're at it, there should be the opt in / opt out of usage / bug report tracking instead of having that in settings.

**Comment by rabble** [comment]
![](https://files.slack.com/files-pri/TDR0MCDJN-F01MW2TUKRA/image.png)

**Comment by martindsq** [comment]
See #521
