### ISSUE TITLE
lost access to my profile

### ISSUE THREAD

**Issue by sokraenkel** [planetary-social/planetary-ios#220]
There is an error while starting the app, now it seems I've logged out but there is no option to log in, just to start a new account. How can I regain access?

**Comment by rabble** [comment]
Hey @sokraenkel,

that shouldn't happen, it stores your key in your keychain managed by apple's iOS. Can you get the logs from the debug menu and post them so we can look at what happened.

-rabble

**Comment by irisdelaluna** [comment]
Hi @sokraenkel, sorry to hear you cannot log in. You should be able to access debug menu by shaking your phone when the app is open - your identities are listed in "Configurations" section - if your profile is listed there, then tap on it and then tap "Select" in the top-right corner - if your profile isn't there, then please send us the debug logs as @rabble suggested, we should be able to track down what went wrong.

**Comment by mplorentz** [comment]
Closing this as it has been almost a year since the last update.
