### ISSUE TITLE
Upgrade go-ssb libraries to use the current version

### ISSUE THREAD

**Issue by rabble** [planetary-social/planetary-ios#226]
The current edge of go-ssb supports EBT, Out of Order message requests, private encrypted groups, and a host of other things. We should upgrade the go-ssb planetary uses to take advantages of these innovations. 

Check to see if we can make go-ssb prioritize the user's feed. 

We need to pass in a list of pubs for the new pubs for go-ssb to connect to.

**Comment by boreq** [comment]
This is in theory done. The library was bumped and the project compiles. See #337 for some potential problems. The branch for those changes is [bump-version](https://github.com/planetary-social/planetary-ios/tree/bump-version).

Currently the main remaining problem that we are tracking is #421.
