### ISSUE TITLE
New User Experience: create script for pre-loading blobs for profiles and other important images

### ISSUE THREAD

**Issue by rabble** [planetary-social/planetary-ios#230]
2021/02/24 22:23:46:363  Preloading blob &R14x5a55lohnjAJ1jjVb2lq8KI1iARDHTmvBv17bcDY=.sha256...
2021/02/24 22:23:46:367  Blob &R14x5a55lohnjAJ1jjVb2lq8KI1iARDHTmvBv17bcDY=.sha256 was preloaded successfully.
2021/02/24 22:23:46:368  Preloading blob &dmWSXYgdf274mdAHddOFnKpuO/pg0Zhh5s5LQz3IuR8=.sha256...
2021/02/24 22:23:46:370  Blob &dmWSXYgdf274mdAHddOFnKpuO/pg0Zhh5s5LQz3IuR8=.sha256 was preloaded successfully.
2021/02/24 22:23:46:371  Preloading blob &QBHOjTiUIH9qoW2jyHRupxEjIOTZBkcr+sNu07VBa4U=.sha256...
2021/02/24 22:23:46:374  Blob &QBHOjTiUIH9qoW2jyHRupxEjIOTZBkcr+sNu07VBa4U=.sha256 was preloaded successfully.

We need to update the feed serialization script use in builds to also grab and update the blobs.

**Comment by martindsq** [comment]
Not needed.
