### ISSUE TITLE
Connected Peers UI: Display status on connections for peers in the profile side bar

### ISSUE THREAD

**Issue by rabble** [planetary-social/planetary-ios#254]
Link to Figma file: https://www.figma.com/file/6oTsbY3vHME19RNtgSGdAw/Planetary-Design-Plan?node-id=523%3A17199

View only link to figma file.
https://www.figma.com/file/6oTsbY3vHME19RNtgSGdAw/Planetary-Design-Plan?node-id=523%3A17199

**Comment by setch-l** [comment]
Matt would like to prioritize this because it will help debug the replication issue.
