### ISSUE TITLE
Feed Enhancement: Hide posts with unloaded images from Discover tab

### ISSUE THREAD

**Issue by Chardot** [planetary-social/planetary-ios#258]
As a user, I want posts with unloaded images to be hidden in the Discover tab, so I can have a more pleasant experience while discovering content.

This is what we're trying to avoid:

Also there are posts with attached video and audio which are not being displayed correctly, so we need to figure out how to display those.

![IMG_1679](https://user-images.githubusercontent.com/477835/148582246-b738d530-6e1a-47c7-ac90-174981e3299b.PNG)

**Comment by setch-l** [comment]
@Chardot - Can we instead show a placeholder image for those media items that don't load? Or do you think we should remove these all together bc it's the discover tab?

**Comment by Chardot** [comment]
@setch-l I would hide these in the Discover tab, otherwise we would be allowing for a dead end user experience through this screen. Since the purpose of this screen is to discover content, I would optimize for the content we **can** display.

**Comment by rabble** [comment]
blobs are loading better now and this isn't an issue.
