### ISSUE TITLE
Pubs: Planetary pubs/communities cannot be joined

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/planetary-ios#262]
Steps to reproduce:
1. Launch fresh install of Planetary 1.0.16
2. Go through onboarding flow
3. Go to the directory tab
3. Follow any pub in the Communities section
4. Sometimes you need to wait up to 70 seconds

Then I got this error:
![IMG_0143](https://user-images.githubusercontent.com/1165004/154121845-d06eda83-d001-4248-998b-54fd60213e68.jpg)

Bugsnag link: https://app.bugsnag.com/verse/planetary/errors/61dc5b602139440008b6c6c2?event_id=61dc5b60008bde9f71930000&i=sk&m=nw

_Observed on prod 1.0.15 and TestFlight 1.0.16 (296)_

**Comment by mplorentz** [comment]
Martin said:

> The app redeems invites to our pubs on onboarding. These invites have a limit, so there is a chance that we already reached the limit and have to generate new invite link...

I bet the Crypto Pub invite has reached its limit.

**Comment by rabble** [comment]
We can issue new invite tokens in to the code, i think they were set at 1000 as it was a stop gap. Before we had a faucet for requesting new invites vs having them hard coded but it had problems.

**Comment by mplorentz** [comment]
Update: I am also seeing this for the Monero pub. Probably good to check them all when we get to this.

**Comment by mplorentz** [comment]
I tried all the featured communities in the directory and this is happening for all of them.
