### ISSUE TITLE
@Mention drawer will not go away

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/planetary-ios#268]
When @-mentioning a user in a post, the autocomplete drawer does not go away after a name is selected.

Steps to reproduce:
1. Start a post (or reply to an existing one)
2. Type the `@` character
3. Select a name from the autocomplete drawer
Expected: the autocomplete drawer disappears.
Actual: the autocomplete drawer is not dismissed until you leave the screen.

https://user-images.githubusercontent.com/1165004/149213777-d0ca1d8f-fe0e-495f-8e4f-6cc4c615d68f.MP4

**Comment by rabble** [comment]
We also have an issue where the suggested mentions aren't very smart. It should list the mentions of people participating in the thread first, as those are the most likely to be mentioned.

**Comment by mplorentz** [comment]
@rabble I opened #312 to track that issue. See also: #313.
