### ISSUE TITLE
Tech Debt: Refactor/Fix GoBotOrderedTests in the Swift Layer

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/planetary-ios#269]
There are several test in the `GoBotOrderedTests ` file that fail sometimes. I am not going to fix them right now for several reasons:
- I can't reproduce most of the failures locally
- I can't run individual test because they depend on the previous tests running
- These tests will likely need significant changes after updating the go bot (#226)

After #226 we should refactor these tests to fix the above issues.

**Comment by martindsq** [comment]
Wait for scuttlego

**Comment by rabble** [comment]
@boreq should remove the tests that don't make sense for scuttlego.

**Comment by boreq** [comment]
Tests are not getting removed I think.

**Comment by mplorentz** [comment]
Yes let's fix these. Probably makes sense to do them as part of the scuttlego upgrade project or as a fast-follow.

**Comment by boreq** [comment]
Do we know which tests this was referring to specifically?

**Comment by boreq** [comment]
The commented out test code specifically tests deleting posts (not supported) and private messages (not supported). I am deleting this test code as the entire point of git is that you can just restore it later.

**Comment by boreq** [comment]
The tests seem to work now and I improved them slightly by making them clean up after themselves. Unless someone objects or has a good idea what to do here I will be closing this ticket.
