### ISSUE TITLE
Revive blocking service

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/planetary-ios#275]
Notes from Feb 24
Martin suggested we get rid of blocking service and implement with normal messages in SSB. 
Might be a longer term fix. 
May need to revive existing blocking service in the short term.

**Comment by rabble** [comment]
Theh blocking service is running but we need to fix how we update it and manage blocks.

**Comment by mplorentz** [comment]
We should also figure out why Google Cloud SQL database, which is used by the block service, is costing us so much money, and make it cheaper. [Slack context](https://planetary-app.slack.com/archives/CP4D5FQ87/p1644598080696969)

**Comment by mplorentz** [comment]
I manually blocked `@hoSGJQoxNZrN52hZ3AB2iA8WpgqMcIwqIH0mVuGbBVk=.ed25519` on all the pubs this morning. We can block this account with the block service as well when we get it running.
