### ISSUE TITLE
Fix image slider paginator

### ISSUE THREAD

**Issue by Chardot** [planetary-social/planetary-ios#276]
As a user, I want to see the dots inside the paginator container, so that I can understand which image I'm currently browsing.

This is how it currently looks:
![Image from iOS (1)](https://user-images.githubusercontent.com/477835/149827989-5a1d5d4c-d0ff-4018-9afe-1fdaba7581aa.jpg)
The dots should appear vertically centered inside the container.

**Comment by rabble** [comment]
fixed
