### ISSUE TITLE
Follow button dissapearing upon navigating out and back into profile view

### ISSUE THREAD

**Issue by Chardot** [planetary-social/planetary-ios#277]
As a user, I want to see the follow button on a user's profile not dissapear, so that I can follow them any time regardless of my browsing activity.

Currently, when I browse to the profile view for a user I don't follow, I can see the follow button. But if I check who they're following and then go back to the profile, the follow button is gone.

Here's a demo:

https://user-images.githubusercontent.com/477835/149828898-f79e9b7e-e2ea-4df5-9f41-f469fbaaaed0.MP4

**Comment by rabble** [comment]
Doesn't seem be a bug any more.
