### ISSUE TITLE
Eliminate 3rd Party Data Sharing: Research elimination of third-party data sharing

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/planetary-ios#280]
If we hosted something like PostHog (analytics) and Zendesk (support) ourselves, then we would no longer be sharing any data with third parties. This would be a great privacy feature. We should research alternatives and estimate the cost to switch.

**Comment by martindsq** [comment]
this is handled with three seperate tickets, remove zendesk #219, move posthog to selfhosted, and bugsnag
