### ISSUE TITLE
UI Enhancement: Make 💜 smaller

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/planetary-ios#287]
The purple hearts we show when a user likes a post are way too big. Eventually we should support arbitrary reactions (#286), but until then it would probably be good to make these smaller.

**Comment by nsantini** [comment]
Worth mentioning that in other clients like Manyverse, the Planetary the Purple Heart shows as a regular thumbs up reaction

**Comment by setch-l** [comment]
Currently - liking a post and adding a single emoji display as a large image in the reply. 
Expected: Liking a post should be displayed as a like
Posting a message with a single emoji should display as a large image.
