### ISSUE TITLE
BUG: Expanded cells break after scrolling

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/planetary-ios#288]
Steps to reproduce:
1. Find a post with replies.
2. Find a reply with the "see more" button at the bottom.
3. Tap "see more"
4. Scroll to the top of the thread
5. Scroll back down
Expected: cell is still expanded
Actual: the cell content is cut off

https://user-images.githubusercontent.com/1165004/150402157-f5c4ab15-c37a-4a9a-a7a6-2f48cece55f4.MP4

**Comment by martindsq** [comment]
Should be fixed as part of #744 swiftui work.
