### ISSUE TITLE
Tapping elipse menu on Your Profile on iPad freezes app

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/planetary-ios#296]
# Steps to reproduce
1. Launch Planetary on iPad
2. Open Your Profile
3. Rotate iPad to landscape orientation
4. Tap the ellipse menu in the top right
Expected: menu opens with options to share profile
Actual: UI freezes, rotating the iPad breaks the UI. _Observed on prod 1.0.16._

[video](https://user-images.githubusercontent.com/1165004/150814489-9dc86269-1464-4ebd-9306-0091bf133262.MP4)

**Comment by kode54** [comment]
Log output of doing this:

```
2022-02-04 01:20:37.621875-0800 Planetary[70718:505670] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
	(Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSAutoresizingMaskLayoutConstraint:0x6000002322b0 h=--& v=--& UIView:0x160b5c8e0.width == 0   (active)>",
    "<NSLayoutConstraint:0x6000002320d0 UIView:0x160b5c8e0.width == _UIAlertControllerView:0x15765e170.width   (active)>",
    "<NSLayoutConstraint:0x600000232a30 UIView:0x1576992b0.width == 270   (active)>",
    "<NSLayoutConstraint:0x6000002c4500 _UIAlertControllerView:0x15765e170.width >= UIView:0x1576992b0.width   (active)>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x600000232a30 UIView:0x1576992b0.width == 270   (active)>
```

I'll attempt to debug it.

**Comment by kode54** [comment]
Figured it out. The popoverPresentationController is locking up because sourceView is being assigned the view handle for the popup itself, which is incorrect. It should be assigned the source view that invoked the popup.

**Comment by mplorentz** [comment]
Thanks for the debug help @kode54. This sounds pretty easy to fix. Taking a look now 👀 .
