### ISSUE TITLE
BUG: The notification tab does not refresh automatically

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/planetary-ios#297]
Tapping on the notification tab only shows your old notifications. This makes it feel broken when you get a notification in-app, then tap the notifications tab and it isn't there. We should refresh it when you tap or maybe when the app receives the notification.

**Comment by rabble** [comment]
This is also true of the other tabs, explore and the for your page.

**Comment by rabble** [comment]
This has gotten bigger because we need to keep track of read status of messages, update the total notifications, etc.... in progress.
