### ISSUE TITLE
Tech Debt: Prevent go-ssb from locking when connecting to pubs

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/planetary-ios#301]
This is a placeholder so we don't forget to file this in the appropriate go-ssb repo in the future.

The go-ssb library locks itself and won't respond to other procedure calls while attempting to establish a TCP connection to a pub server to redeem an invitation. More details in #272.

**Comment by rabble** [comment]
shouldn't be an issue in scuttlego. 

We should remove the dumb workaround we created in swift after we switch from go-ssb to scuttlego.

**Comment by boreq** [comment]
This is definitely not an issue in scuttlego however the calls to `Connect` are blocking and will block until connection succeeds. If we want to change that because swift is not happy about it then we need a separate ticket.
