### ISSUE TITLE
BUG iPad: Fix layout for explore tab on ipad / mac

### ISSUE THREAD

**Issue by rabble** [planetary-social/planetary-ios#311]
At the moment, the explore tab is using pixels for sizing content. This works great on iphone devices, works ok an ipad, and is completely terrible on the mac. I think it needs something which is more scaled, it doesn't work with more than 4 or 5 columns. 
<img width="797" alt="Screen Shot 2022-01-27 at 1 47 31 PM" src="https://user-images.githubusercontent.com/76/151276616-a4945e08-d960-4e17-aca2-67c5b1930486.png">

**Comment by martindsq** [comment]
better, but still bad. Will be addressed when we redo the discover tab in swiftui.
