### ISSUE TITLE
BUG: Replying to a root post from a forked identity does not work

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/planetary-ios#322]
Nico thinks he forked his Planetary identity `@/jtNJr7fPpCKZ19IONYAlxeq4JYAGfwBBEZSphD6T9U=.ed25519`. We are able to reply to  message `%rQNJPDDDQSxyQ9oJd5vVAC9j8r502ZHrILthDVLE6OU=.sha256` (a message from the forked feed) from other clients, but his new planetary identity fails to post a reply:
<img src="https://user-images.githubusercontent.com/1165004/151674311-774a3c1d-5c11-4ae5-a8f5-4dd6b832f29d.jpg" width="300" />

Maybe if you are trying to reply to a post from a forked feed then maybe we don't expect it to work?  I wonder if Planetary refuses to replicate forked feeds at all? More investigation needs to be done.

**Comment by nico-serko** [comment]
I triggered the error again, and downloaded the latest logs, here is the zip fil
[Nico's logs.zip](https://github.com/planetary-social/planetary-ios/files/7967015/3FDACB84-144C-46C0-8649-012D7AC1F546.zip)
e

**Comment by rabble** [comment]
#wontfix  

This should be addressed by changing the way scuttlebutt handles forked feeds but we won't fix it until then.
