### ISSUE TITLE
Lots of actions lock up the app on Apple Silicon Mac due to conflicting constraints

### ISSUE THREAD

**Issue by kode54** [planetary-social/planetary-ios#323]
Lots of actions will cause the app to outright lock up, like clicking Download Logs, or attempting to change my profile, or attempting to set a different profile picture, or attempting to use the share sheet. I'd be willing to help debug some of these. Or try.

**Comment by rabble** [comment]
Yep, and also see the mac app crash due to memory leaks. First step is to upgrade the go-ssb code. We've got a new ios release in testflight at the moment that catches and eliminates a bunch of these issues.

**Comment by kode54** [comment]
Ah, cool.

**Comment by kode54** [comment]
This is a dupe of #296
