### ISSUE TITLE
BUG: Adding a photo after removing one, does not add the photo

### ISSUE THREAD

**Issue by setch-l** [planetary-social/planetary-ios#344]
Steps to reproduce:
1. open planetary
2. Click add post
3. Click on image icon
4. Take photo with camera 
(note the camera centering is a bit off and you cannot adjust the photo crop once taken)
5. Click use photo
6. Click on photo and select remove photo
7. Click on photo icons to add a new photo
8. Take the photo
9. Click use photo button
Issue: No photo appears on the post. 
If you add some text and then click add photo again - you get both photos to appear.
![Screenshot 2022-02-04 at 3 17 52 PM](https://user-images.githubusercontent.com/6765558/152605074-80210237-6ab5-43d2-a256-9ce541558dfd.png)

**Comment by rabble** [comment]
related to image selector code, and moving publishing screen to using swiftui and markdown niceness.

**Comment by martindsq** [comment]
Closed this as [completed](https://github.com/planetary-social/planetary-ios/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3Acompleted) in https://github.com/planetary-social/planetary-ios/pull/1261
