### ISSUE TITLE
BUG Replication: Syncing and updating for replies is slow even when they are on the same local network.

### ISSUE THREAD

**Issue by rabble** [planetary-social/planetary-ios#347]
I posted something on planetary ios, and it showed up on patchwork first, but didn't on planetary desktop yet at all. In patchwork i see three replies, in planetary ios only one, but 2 hours late. And in desktop not at all. There's some work needed to be done trackdown where the problem is.
<img width="1136" alt="Screen Shot 2022-02-08 at 12 06 27 PM" src="https://user-images.githubusercontent.com/76/152887489-431489d0-e332-4507-bb5d-ef8e6c86b1b2.png">
<img width="797" alt="Screen Shot 2022-02-08 at 12 06 08 PM" src="https://user-images.githubusercontent.com/76/152887499-6f860153-6742-417e-ae6a-5c2057a80945.png">
![IMG_4633](https://user-images.githubusercontent.com/76/152887614-6d0c2233-a238-426a-9884-0ad7193cdff0.PNG)

**Comment by mplorentz** [comment]
I would call this blocked by #337 though, because upgrading go-ssb is changing how replication works.

**Comment by nsantini** [comment]
Here are my latest logs. It was not updating for quite a while, then I got a bunch of gossip, and then nada again :(
[DDB30705-5DB7-45F8-B28D-49AC821BF9FE.zip](https://github.com/planetary-social/planetary-ios/files/8128020/DDB30705-5DB7-45F8-B28D-49AC821BF9FE.zip)

**Comment by mplorentz** [comment]
This is working much better now with EBT replication. Closing.
