### ISSUE TITLE
BUG iPad: Photos expand past screen bounds on iPad

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/planetary-ios#351]
Photos displayed on the iPad, especially in landscape orientation, can get stretched to really absurd dimensions. I think we should at least lay these out using an "aspect fit" mode with a max height. Even then, they might look weird in landscape so maybe an alternate layout is necessary.

https://planetarysupport.zendesk.com/agent/tickets/380

Related to #233

![09B2332D-9320-46B9-ADCA-336235540795_L0_001](https://user-images.githubusercontent.com/1165004/153241938-f39a839a-f947-4cd3-bae5-258151a50846.png)

**Comment by rabble** [comment]
We need to replace a new viewer #88  and also this will be fixed with swiftui. #744
