### ISSUE TITLE
BUG Replication: Replication stops happening

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/planetary-ios#354]
@setch-l was seeing an issue where her phone was not replicating data from the system pubs. We are not sure yet how it got into this state, but when we got on Zoom it magically fixed itself. It's possible that pulling to refresh on the home feed is what fixed it. I'm going to investigate further.

You can see in the logs that her device has been trying and failing to connect to the system pubs. See for example the Feb 8 logs and the Feb 10 logs have the same number of messages in go ssb, and all connection attempts that fail with messages like:
```
botError muxrpc connect to Peer(tcpAddr: "two.planetary.pub:8008", pubKey: "@7jJ7oou5pKKuyKvIlI5tl3ncjEXmZcbm3TvKqQetJIo=.ed25519") failed
```
[logs while things were broken](https://github.com/planetary-social/planetary-ios/files/8043702/8E6FE61C-8A2F-4D4E-B37D-EF0DD0B569BA.zip)
[logs after they started working again](https://github.com/planetary-social/planetary-ios/files/8043704/1A302C30-690A-4C43-9A22-50528AEB7AF3.zip)

I may need to go ahead and do #306 to get more useful information.

**Comment by mplorentz** [comment]
See also #347

**Comment by rabble** [comment]
Some problem in Margaret and we won't fix it because we're moving to raptor.

**Comment by rabble** [comment]
a lot has changed and this doesn't seem to be an issue any more.
