### ISSUE TITLE
Question about db compatibility

### ISSUE THREAD

**Issue by Scott20222** [planetary-social/planetary-ios#357]
Hello, I saw the built-in go-ssb core in ios planetary from the planetary channel on patchwork, I have a question, is this compatible with your db2 pub? Is the built-in pub link the one that uses the db database?Thanks.

**Comment by mplorentz** [comment]
Hi @Scott20222! Yes we embed [cryptoscope/ssb](https://github.com/cryptoscope/ssb/) in the iOS app. It's a full scuttlebutt node that implements the whole protocol, so in theory it should be compatible with any other node.

> is this compatible with your db2 pub?

Are you referring to https://github.com/planetary-social/ssb-server2? I think in theory these should be compatible, although IIRC @nichoth was having some issues with db2 so I'm not sure if ssb-server2 is fully functional yet. @nichoth could you weigh in here?

> Is the built-in pub link the one that uses the db database?

I'm not sure what you mean by the built-in pub link. Are you referring to our Planetary system pubs? The system pubs are running the original javascript ssb-server software, in the form of [ahdinosaur/ssb-pub](https://github.com/ahdinosaur/ssb-pub).

**Comment by Scott20222** [comment]
Thank you for your feedback, it helped us a lot
