### ISSUE TITLE
Dev Tools: Fix automatic dSYM upload to bugsnag

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/planetary-ios#360]
We need to upload dSYMs to BugSnag to get detailed information on crashes. We have a script that is supposed to do this in the app but it doesn't appear to be working.

**Comment by rabble** [comment]
That's weird, it works for me, i must have done something to configure it in xcode locally.

**Comment by mplorentz** [comment]
This was fixed when @martindsq created the Secrets package.
