### ISSUE TITLE
Hashtag page: Add a search bar to hashtag view

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/planetary-ios#367]
We should allow users to search the hashtag page for a particular hashtag. This is much easier than implementing app-wide search.

**Comment by rabble** [comment]
Needs design from @Chardot

**Comment by Chardot** [comment]
Here's my proposal for the Channels screen

![Screenshot 2022-05-17 at 21 28 52](https://user-images.githubusercontent.com/477835/168894563-69cd2ba6-dbf6-42be-b13d-feafe6caca47.png)

Note that I added a mosaic component which shows the last 4 images posted on each channel. If there are not enough images to show, it defaults to the profile images of the most recent users who posted. If there are less than 4 images/users, it defaults to the latest image/user who posted.

I also added the number of «shares» (posts) on each channel.
