### ISSUE TITLE
Watch a Thread: Allow users to subscribe to a thread

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/planetary-ios#368]
As a user I want to get notified about replies to a thread without replying to it myself. This is especially important with the way we currently sort the home feed because replies to a post do not bring that post back to the top of the feed which means they may never be seen. We could add a function where the user subscribes or "watches" a thread and then gets a notification whenever it is replied to.

**Comment by martindsq** [comment]
not a big issue but we should impliment this with either a private tag or vote Not a priority.
