### ISSUE TITLE
BUG: Incorrect shortening of messages containing markdown

### ISSUE THREAD

**Issue by boreq** [planetary-social/planetary-ios#388]
The messages in the main feed are shortened to a specific number of characters. A full message is available after clicking on one of the messages in the main feed. The mechanism for shortening messages is naive and can end up cutting markdown formatting sequences in half. This results in the message being rendered incorrectly.

<img width="513" alt="Screenshot 2022-02-23 at 17 53 46" src="https://user-images.githubusercontent.com/1935975/155368421-560e3486-9daf-4f04-91fb-f74caffa1ace.png">

The fix could either involve implementing a more complicated algorithm for cutting the message (sounds complicated) or simply rendering the whole message and instead making the element in which the message appears shorter cutting the part of the message.

**Comment by mplorentz** [comment]
This could probably be addressed alongside #288.

**Comment by martindsq** [comment]
should be fixed with #744

**Comment by martindsq** [comment]
dupe
