### ISSUE TITLE
Support all feed formats in Connected Peers UI

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/planetary-ios#400]
Currently the connected peers list (#254) shown in the side menu will only show peer details like name and profile image if the peer has an ed25519 feed. This is due to the fact that the go function `ssbBotStatus()` includes the currently connected peers in this format `net:1.2.3.4:8008~shs:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=`. Where `AAA` is the public key. But feed IDs are stored in SQLite fully qualified like this `@AAAAA=.ed25519`. 

I think SQL is what should change here, but I'm not sure. It's not clear to me why most places in SSB we include the `=.ed25519` but [multiserver addresses](https://github.com/ssb-js/multiserver#address-format) do not.

**Comment by rabble** [comment]
invalid but needs to be defined by ssb's multifeed implementations.
