### ISSUE TITLE
BUG: Zombie threads

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/planetary-ios#403]
The app seems to be leaving threads open that are never closed. This drains system resources and could potentially cause other problems (like iOS killing Planetary as soon as it is backgrounded).

Steps to reproduce (observed on 1.0.20)
1. Build and Run the app using Xcode
2. Leave Planetary running for 1-2 minutes.
Expected: Planetary is using a reasonable amount of threads
Actual: There are a large number of runtime.pthread_cond_wait_trampoline threads that aren't doing anything.

**Comment by rabble** [comment]
due to us using lots of go co-routines. 

we should limit gothreads to 2x the number of cores.
