### ISSUE TITLE
Set up/fix Crowdin translations

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/planetary-ios#408]
We need to fix our Crowdin translation service integration and set up team members as translators.

Maybe we should pick a service other than Crowdin.

**Comment by comradekingu** [comment]
Happy to help if you pick some variant of Weblate, or any libre solution that doesn't leak info about users.

**Comment by mplorentz** [comment]
Just got this email from Apple, it looks like one of our locales is not supported. Maybe we can fix this as part of this ticket:
```
Dear Developer,

We identified one or more issues with a recent delivery for your app, "Planetary Social" 1.0.22 (313). Your delivery was successful, but you may wish to correct the following issues in your next delivery:

ITMS-90176: Unrecognized Locale - - The locale names used in localization directories at ( 'Payload/Planetary.app/sr-SP.lproj' ) are invalid. iTunes supports BCP47 but not the UN M.49 specification. Refer to the Language and Locale Designations guide at https://developer.apple.com/library/content/documentation/MacOSX/Conceptual/BPInternational/LanguageandLocaleIDs/LanguageandLocaleIDs.html for more information on naming your language-specific directories.

After you’ve corrected the issues, you can upload a new binary to App Store Connect.
```

**Comment by mplorentz** [comment]
@comradekingu do you have specific privacy concerns with Crowdin or is that more of a general concern?

**Comment by comradekingu** [comment]
@mplorentz Yes https://support.crowdin.com/cookies/ Translators have to be over 18 to even agree to the terms.
My basic concern is not being able to span large amounts of strings at once, see more languages at once, and generally the idea of voting past the initial mover meaning changing strings requires an extra account, or waiting around for a third translator.
It doesn't handle fuzzy strings or locales correctly. The list goes on.
To add insult to injury, it isn't possible to browse strings without logging in.
