### ISSUE TITLE
Test Posting Private messages to Planetary users

### ISSUE THREAD

**Issue by setch-l** [planetary-social/planetary-ios#409]
In order to determine what is happening with private messages please take the following steps:
Use a non-Planetary client that supports private messaging
Send a private message to a Planetary user 

See if:
- can the Planetary user decrypt the message (or is the message encrypted at all)
- can the Planetary user reply to the message? 
- If they can reply, what is the visibility of the reply in Planetary AND the originating client.

**Comment by yanniskatsaros** [comment]
Hello! Apologies if this is not the right place for this question, new SSB and Planetary user here. I’m using the Planetary iOS app and a friend I’m following is on a different SSB client (Manyverse I believe?) He said he sent me a private message but I can’t seem to find it anywhere in my feed or elsewhere on the app. I’ve made sure that everything has synced and tried refreshing my feed multiple times throughout the day, leaving my app open to ensure syncing takes place. Can you please help nudge me in the right direction on this? Thank you!

**Comment by yanniskatsaros** [comment]
> Hello! Apologies if this is not the right place for this question, new SSB and Planetary user here. I’m using the Planetary iOS app and a friend I’m following is on a different SSB client (Manyverse I believe?) He said he sent me a private message but I can’t seem to find it anywhere in my feed or elsewhere on the app. I’ve made sure that everything has synced and tried refreshing my feed multiple times throughout the day, leaving my app open to ensure syncing takes place. Can you please help nudge me in the right direction on this? Thank you!

Update: I missed this from the [README](https://github.com/planetary-social/planetary-ios#functionality-implemented-in-planetary-with-only-debug-or-api-interface), my apologies. I suppose the question should be, how do enable Debug mode in the app, is this possible from a prod build downloaded from the App Store?

**Comment by mplorentz** [comment]
Hi @yanniskatsaros, this is a fine place to ask! Unfortunately the README was incorrect. Private messages are not implemented in debug mode. This is a feature we would like to implement soon. If you'd like you can watch ticket #964 to get an email when it is done.
