### ISSUE TITLE
Display likes from other clients

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/planetary-ios#410]
It looks like Planetary is only displaying likes (or 'vote' posts) from other Planetary clients. We should render them from other clients as well.

As an example, I am only seeing two likes on this post from rabble: `%V5m1QkfEdHx7HlJxo9gDmpsbvQPXRMlUwyLi4jpM7LQ=.sha256`

But in Patchwork (where I follow a very similar list of people) I see 15 likes.

**Comment by rabble** [comment]
Display the 'vote' content instead of just our one emoji.
