### ISSUE TITLE
Swipe down to escape full-screen image view

### ISSUE THREAD

**Issue by Chardot** [planetary-social/planetary-ios#413]
As a user, I want to [swipe down|tap outside the image boundaries] from a full screen image view, so I can escape the view and continue looking at other content more easily.

With the current image viewer, after tapping on an image in a post to view it full screen, the only way to escape that view is to tap on the X at the top left of the screen, as shown:

![IMG_3461](https://user-images.githubusercontent.com/477835/157478573-127307fb-eb1f-46fc-ae3d-b1433f9766e1.PNG)

It would be great to trigger that same functionality by:

1. Swiping down anywhere on the screen to ecape the full screen image view
2. Tapping anywhere outside the image boundaries

In order to make the image boundaries more evident so that the user knows where to tap to escape this view, we could lower the opacity of the black background to around 90%. Adding a 20% gaussian blur filter would also help.

@mplorentz What do you think about this?

**Comment by rabble** [comment]
Related to #88  which is to replace the image / media viewer
