### ISSUE TITLE
Create new community pubs

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/planetary-ios#419]
We are going to try another round of community pubs to gauge user interest with this format. They will be focused on:
- gardening
- poetry
- fungi
- cooking
- spanish-language

**Comment by mplorentz** [comment]
@Chardot it would be great to get images for our existing two pubs if you have time: crypto and FLOSS pubs.

**Comment by Chardot** [comment]
@mplorentz Here's two more icons for Russian and Ukrainian language specific pubs:

[Pub Icons - Russian and Ukrainian.zip](https://github.com/planetary-social/planetary-ios/files/8410678/Pub.Icons.-.Russian.and.Ukrainian.zip)
