### ISSUE TITLE
Support Bendy Butt & Gabby Grove feed formats

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/planetary-ios#429]
Gabby grove is an alternative feed format which we used to support. Support for it was disabled in #425 due to large changes in the way feed and message identifiers are formatted, but we could bring it back.

**Comment by rabble** [comment]
We should consider supporting bamboo instead / in addition? Gabby Grove has a bunch of nice features but i think only go-ssb supports it.

**Comment by boreq** [comment]
Just to clarify this is what the protocol documentation states:

>Clients, for compatibility reasons, have a main classic feed alongside the root metafeed. 

This implies that every client should have a classic feed as their main feed. What does this mean in the context of gabby grove or bamboo? I thought that those are only supposed to exist in the form of metafeeds.

**Comment by rabble** [comment]
This will be addressed in scuttlego and specs need to defined.
