### ISSUE TITLE
Change the build process so that .a files don't have to be commited to the repo

### ISSUE THREAD

**Issue by boreq** [planetary-social/planetary-ios#436]
Currently we commit the .a files to the repository. Those files are an artifact of our build process. Ideally we shouldn't have to commit them to the repo as:
- they are large
- someone may forget to rebuild them
- they create noise in the pull requests

We would like to change our build process (probably the xcode configuration) so that those files are just built on the fly as needed.

**Comment by mplorentz** [comment]
This is complete on `bump-version` via #438.
