### ISSUE TITLE
Unexpectedly presented onboarding screens, which failed with error.

### ISSUE THREAD

**Issue by quickdudley** [planetary-social/planetary-ios#439]
Yesterday I opened Planetary for the first time and there was an error dialog which if I recall correctly were labeled "Reset" and "Refresh". The dialog itself didn't fully explain the difference so I picked Reset (assuming it meant restart the app).

Then I was presented with the onboarding screens (pick year of birth and display name). But after picking my display name there was another error dialog with text "Oh no! Something went wrong! The operation couldn't be completed. (Planetary.Onboarding.StartError error 1.)" with options "Try Again" and "Start Over". Both options just took me back to the first onboarding screen.

After deleting and reinstalling Planetary, I was able to complete the onboarding process as expected. Unfortunately I had not backed up my identity.

**Comment by mplorentz** [comment]
Hey @quickdudley, I'm so sorry to hear you hit this issue. It sounds like you hit #332, where go-ssb does not shut down cleanly and for some reason can't recover using its journals. 

We are currently working on upgrading our version of go-ssb to the latest version and we are hoping this will resolve the issue.

You may be able to still recover your old identity if you want to try. Planetary saves your secret key to the system keychain, so even after deleting the app it should still be in there. You can try switching to your old identity by opening the side menu -> Settings -> Advanced Settings  -> Dangerous and Powerful Debug Menu. If you scroll down on the debug menu you will see a Configurations section. If your old profile is there you can tap on it and tap "Select" in the top right. Then I would force-quit and restart the app. Then give Planetary some time to resync your feed from the network. It is very important not to take any actions that would fork your feed during this time like posting, liking, following, unfollowing, etc. to avoid [Forking your feed](https://github.com/planetary-social/planetary-ios/wiki/Forked-Feed).

We are trying to make restoring your feed a safer process in the near future. Please feel free to reach out if you have any trouble.

**Comment by quickdudley** [comment]
Thanks @mplorentz, that makes sense. Unfortunately I had already noticed a second identity in there, but at the time it had the name I'd entered during one of the times the re-onboarding crashed so I assumed it wouldn't be anything useful.
