### ISSUE TITLE
fix statistics in the new upgraded go-ssb

### ISSUE THREAD

**Issue by rabble** [planetary-social/planetary-ios#449]
The new statistics view (the one which lists connected peers and the number of replicated messages) seems to somehow crash and the data is no longer displayed.

**Comment by boreq** [comment]
Our Swift layer calls the following functions in the bindings to display the statistics in the user interface:
- `ssbBotStatus`
- `ssbOpenConnections`
- `ssbRepoStats`

Those functions call the following go-ssb code:
- `sbot.Status()`
- `sbot.Network.GetConnTracker().Count()`
- `sbot.GetMultiLog()` -> `...List()`, `sbot.ReceiveLog.Seq()`, `sbot.ReceiveLog.Get()`

**Comment by boreq** [comment]
The lockup seems to be occuring here.

https://github.com/cryptoscope/ssb/blob/27a936da805d127f22af539760849e03f07358e6/blobstore/wants.go#L212

**Comment by boreq** [comment]
This seems to be linked to the lock being engaged around here and never released. 

https://github.com/cryptoscope/ssb/blob/27a936da805d127f22af539760849e03f07358e6/blobstore/wants.go#L77-L93

If I am not wrong the lock is engaged for the entire duration of downloading a blob from various peers?!

**Comment by boreq** [comment]
Related to #422.

**Comment by boreq** [comment]
Possibly fixed here, needs further investigation. https://github.com/boreq/ssb/commit/ba78c6bf2aa98d4075ce83479deab8cc380a5029
