### ISSUE TITLE
Investigate go-ssb panics in bugsnag

### ISSUE THREAD

**Issue by boreq** [planetary-social/planetary-ios#457]

**Comment by boreq** [comment]
Relates to #505. This PR should help us diagnose this issue.

**Comment by boreq** [comment]
Blocked till we get the new the new logs from someone.

**Comment by rabble** [comment]
@boreq will check to see if there is any new data in bugsnag

**Comment by boreq** [comment]
Had a look at bugsnag and asked our team members for their logs as some of them appear to have experienced this issue within the last week.

**Comment by rabble** [comment]
wait for scuttlego.
