### ISSUE TITLE
Update user profile to display more information

### ISSUE THREAD

**Issue by rabble** [planetary-social/planetary-ios#458]
A user's profile needs to show more information. It needs to show who's following them, who they follow, who they're blocking, and who's blocking them.

The main feed of a profile needs two options. One their posts, reactions, and follows/blocks. But also the scuttleverse from their perspective.

The planetary database knows what the current user is, but it's equally possible to show a 'home feed' from the perspective of any other. In particular, this is useful for viewing a pub's profile. Users should be able to see all the posts by people who the gardening pub follows. This simply shift will make the pub profile pages useful.  Not only for pubs, we need this for all profiles.

**Comment by rabble** [comment]
This needs a design from @Chardot.

**Comment by boreq** [comment]
Open issue in "done".
