### ISSUE TITLE
Refine memory usage

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/planetary-ios#459]
I set the badger memory usage to something really low during the go-ssb upgrade, but we should go back and figure out what our target memory usage actually is.

**Comment by boreq** [comment]
Related to https://github.com/cryptoscope/ssb/pull/147.

**Comment by mplorentz** [comment]
The 1.2.0 (321) build runs out-of-memory pretty consistently around 1GB on my phone. Maybe we should try to trim badger down to 500MB of usage and see how that goes?

**Comment by boreq** [comment]
Small memory fix https://github.com/boreq/ssb/commit/7f471b8512c3299640bcd5376b106576f7d5003e, this is now available on `release/1.2.0`.

**Comment by mplorentz** [comment]
I tested the memory fix and while it works fine on test profiles when I run it on my main Planetary account it still runs out of memory within a couple minutes and crashes. Going to dump some things I tried below.

I tried changing more of the settings in `badger_ios.go`, but it didn't seem to change the memory usage at all. Maybe I wasn't doing go modules correctly. I've pushed up my changes on the `test-badger-memory-usage` branch, which also includes a fix for the Makefile not rebuilding when `go.mod` or `go.sum` change.

[Here](https://github.com/mplorentz/ssb/blob/63d7730fad76ed61f4e1b02d5645f717aab1995a/repo/badger_ios.go) are the options I tried. I tried to set things ridiculously low just to see if they would change anything. I also dug up a few links that helped me make sense of some of the options. I will link them here in case you haven't seen them @boreq.
- https://discuss.dgraph.io/t/clarify-memory-usage-section-in-readme/8733/8
- https://github.com/dgraph-io/badger/blob/2a9a524b649b4e149af17e887fe6352edcf5b52e/options.go
- https://dgraph.io/docs/badger/get-started/#memory-usage

These seem out of date though. Maybe we need to open a thread on the badger forums, as the maintainers seem willing to engage.

I also noticed that the big jumps in memory usage come each time go-ssb is logging stuff like this:
```
ts="2022-04-27 23:57:45.3365280 (UTC)" level=debug plugin=gossip event=gossiprx fr=<@srjL.ed25519> starting=75 received=13 took=20.443236125s
ts="2022-04-27 23:57:45.3399200 (UTC)" level=debug plugin=gossip event=gossiprx fr=<@srjL.ed25519> starting=75 received=13 took=11.158897792s
ts="2022-04-27 23:57:45.3562600 (UTC)" level=debug plugin=gossip event=gossiprx fr=<@kS1G.ed25519> starting=1148 received=2 took=11.170548875s
ts="2022-04-27 23:57:45.3830910 (UTC)" level=debug plugin=gossip event=gossiprx fr=<@MvHB.ed25519> starting=24 received=2 took=11.195803209s
ts="2022-04-27 23:57:45.3867280 (UTC)" level=debug plugin=gossip event=gossiprx fr=<@MZ02.ed25519> starting=66 received=2 took=11.199093459s
ts="2022-04-27 23:57:47.2233040 (UTC)" level=debug plugin=gossip event=gossiprx fr=<@Gg1+.ed25519> starting=5 received=4 took=13.042340542s
ts="2022-04-27 23:57:47.2371090 (UTC)" level=debug plugin=gossip event=gossiprx fr=<@XSjn.ed25519> starting=4 received=4
```

**Comment by boreq** [comment]
The easiest way of testing changes locally is this @mplorentz:
1. Clone the `github.com/boreq/ssb` repo to `/somewhere/ssb` so that you have it locally.
2. Edit https://github.com/planetary-social/planetary-ios/blob/release/1.2.0/GoSSB/Sources/go.mod replacing this line:
```
replace go.cryptoscope.co/ssb => github.com/boreq/ssb v0.2.2-0.20220427141232-7f471b8512c3
```
With this line:
```
replace go.cryptoscope.co/ssb => /somewhere/ssb
```
3. Run `go mod tidy` in the directory with the `go.mod` file to make sure everything is ok.

After performing those steps the builds will use the local copy and your changes will be easy to test. After you are done just restore `go.mod` to what it was and run `go mod tidy`.

**Comment by boreq** [comment]
>I also noticed that the big jumps in memory usage come each time go-ssb is logging stuff like this

That is basically whenever it is actually replicating and therefore actively processing messages.

**Comment by boreq** [comment]
Lets make this a ticket for memory usage in general as it seems to be mainly related to things other than Badger.
