### ISSUE TITLE
Create a new Planetary identity

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/planetary-ios#462]
We need to create a new Planetary SSB account. We'll need to update our code so that new users follow the new account instead of the old one. We'll also need to figure out what device the identity will live on and who will be able to post from it.

**Comment by rabble** [comment]
maybe standup cloud oasis based on Nico's new work and put it behind authbasic?

**Comment by rabble** [comment]
This seems like it's done.

> Matt said: "If you have sbot or the ssb-server command line tool installed on your machine, consider running this command to add planetary.rocks to your conn.json which means you will connect directly to it and replicate its messages sometimes: sbot gossip.connect "net:planetary.rocks:8008~shs:l1sGqWeCZRA99gN+t9sI6+UOzGcHq3KhLQUYEwb4DCo="
