### ISSUE TITLE
Planetary iOS app markdown bug - update parser to handle parentheses in URL titles

### ISSUE THREAD

**Issue by qcu** [planetary-social/planetary-ios#48]
Test Flight: Planetary App v 0.9.14 (181)

Current behaviour:

    [@SoapDog (SPX)](@0xkjAty6RSr5uhbAvi0rbVR2g9Bz+89qiKth48ECQBE=.ed25519)
    renders as: @SoapDog @0xkjAty6RSr5uhbAvi0rbVR2g9Bz+89qiKth48ECQBE=.ed25519)
    with only the "@SoapDog" portion as a malformed URL.

Expected behaviour:

    [@SoapDog (SPX)](@0xkjAty6RSr5uhbAvi0rbVR2g9Bz+89qiKth48ECQBE=.ed25519)
    render as a url: "@SoapDog (SPX)"

Apologies if this isn't the correct location for filing Planetary iOS app bug reports. Please redirect.

**Comment by rabble** [comment]
Thanks @qcu for reporting this. We've swapped the markdown library so we should fix this with the next release. Thanks so much for reporting this and helping us beta test the app.
