### ISSUE TITLE
Bundle GoSSB.xcframework in a Swift package

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/planetary-ios#496]
The GoSSB.xcframework doesn't currently allow Go development to work smoothly in Xcode. If you change a .go source file you have to compile Planetary twice to get it to pick up the change. I believe this is because Xcode sets up a hidden "Process XCFramework" step at the beginning of the build before actually building the GoSSB target. I think the only way to get Xcode to build the GoSSB target before running Process XCFramework is to bundle it in a Swift Package.

**Comment by martindsq** [comment]
This is associated to https://github.com/planetary-social/planetary-ios/issues/373
It is already partly made in https://github.com/planetary-social/ssb-ios
This time, I think we would want to include the go source code and project inside to automatically generate the framework

**Comment by rabble** [comment]
This is the solution, maybe, the issue around two pass builds to get go-ssb to pick up the build in xcode.

**Comment by martindsq** [comment]
Duplicate of #373
