### ISSUE TITLE
Some user feeds have incorrect timestamps after migration

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/planetary-ios#520]
When testing 1.2.0 on my main device all of `dinoworm`'s posts showed up with the same `claimed` timestamp, as if they were all posted at the same time. It filled up my home feed with all their posts making it unusable. Weirdly it only seemed to happen for this one user's posts.

**Comment by mplorentz** [comment]
It looks like go-ssb is just returning the wrong timestamp. It looks like some of `dinoworm/@6ilZq3kN0F+dXFHAPjAwMm87JEb/VdB+LC9eIMW3sa0=.ed25519`'s posts have timestamps with more significant digits than usual. I suspect this is messing with go-ssb's json parsing somehow.

Here is some example output from `ssbStreamRootLog`:
```
[{"key":"%BuTtpWRhM9W4N1RL/T+m0EZ8W50iIqj8cMkszx8nf/U=.sha256","value":{"previous":"%GzTDen8RbVZtVgwot3swlFAQ8pkOqqbLKOP5Pyck5fQ=.sha256","author":"@6ilZq3kN0F+dXFHAPjAwMm87JEb/VdB+LC9eIMW3sa0=.ed25519","sequence":13953,"timestamp":5558315026557,"hash":"sha256","content":{"type":"vote","vote":{"link":"%7z5kBSRyoVcgqxP07lZfCKez4KMgP9fAIpl0FYanaA4=.sha256","value":1,"expression":"Like"}},"signature":"/zNdbLy8coceNouxoYmJMJd6xng4sp16AfQv8nbcuyrrVyogI95zC03BkyOTfmVYpTBW65PHRK+8HSkZoQyLDA==.sig.ed25519"},"timestamp":1651842592319,"ReceiveLogSeq":112871,"HashedKey":"36c88738a2f1c5b32a97e76b4ec370a02514b29bcd1b0829bf507e01d1735761"}
...
```

Notice the timestamp inside the "value" dictionary: `5558315026557`, or Sat Feb 19 2146 08:23:46 GMT+0000, 124 years in the future.

But when I fetch the same post from `ssb-server` the timestamp is `1553771682509.004`, or Thu Mar 28 2019 11:14:42 GMT+0000.
```
$ ssb-server get %BuTtpWRhM9W4N1RL/T+m0EZ8W50iIqj8cMkszx8nf/U=.sha256
{
  "previous": "%GzTDen8RbVZtVgwot3swlFAQ8pkOqqbLKOP5Pyck5fQ=.sha256",
  "sequence": 13953,
  "author": "@6ilZq3kN0F+dXFHAPjAwMm87JEb/VdB+LC9eIMW3sa0=.ed25519",
  "timestamp": 1553771682509.004,
  "hash": "sha256",
  "content": {
    "type": "vote",
    "vote": {
      "link": "%7z5kBSRyoVcgqxP07lZfCKez4KMgP9fAIpl0FYanaA4=.sha256",
      "value": 1,
      "expression": "Like"
    }
  },
  "signature": "/zNdbLy8coceNouxoYmJMJd6xng4sp16AfQv8nbcuyrrVyogI95zC03BkyOTfmVYpTBW65PHRK+8HSkZoQyLDA==.sig.ed25519"
}
```

@boreq could you take a look at this?

**Comment by boreq** [comment]
The bug seems to be here https://git.sr.ht/~cryptix/go-toolbelt, this is imported by go-ssb as https://pkg.go.dev/go.mindeco.de/encodedTime. The methods which unmarshal and marshal this type have a bug. 

https://git.sr.ht/~cryptix/go-toolbelt/tree/v1.12.0/encodedTime/millisecs.go#L18-39

**Comment by boreq** [comment]
Added to #533.
