### ISSUE TITLE
Replication stops during migration

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/planetary-ios#524]
When installing 1.2.0 (321) on my main device the go-ssb migration screen never got to 100%. Here is what happened:
> - My own feed gets replicated within ~10 seconds
> - Some other feeds get replicated, then replication stops and no further messages are replicated until I restart the app. It's really consistent. I tested 3 times and every time I end up with exactly 10807 messages in SQLite (only 340 of these are mine). A full resync for me should be around 2,000,000 messages. I put in breakpoints and verified that Swift is doing basically the same connection scheduling ssbConnectPeer() calls it does on main, so I suspect something is wrong in the Go layer.
> - After restarting the app more messages get downloaded but it is very slow. The logs make it look like go-ssb is replicating a lot of messages but they take forever to get into SQLite. I suspect that go-ssb is locking internally and won't really respond to ssbStreamRootLog() calls while it is verifying feeds?

We should figure out how to get the app to replicate smoothly during the migration. If it's still slow we should also consider building in a mechanism to show the migration UI on subsequent relaunches until your feed has fully resynced.

**Comment by boreq** [comment]
Small memory fix https://github.com/boreq/ssb/commit/7f471b8512c3299640bcd5376b106576f7d5003e, this is now available on `release/1.2.0`.

**Comment by boreq** [comment]
This may have been fixed here https://github.com/planetary-social/planetary-ios/commit/59c1df833277c60def3395eff70d85096ffc3692 (https://github.com/planetary-social/ssb/commit/e7b9e0bb689f7ba5a457783ff99bb493bc9e9d4a).

**Comment by boreq** [comment]
It hasn't. There is still a bug where the database enters some invalid state where some contacts are not tracked correctly. This means that replication from some contacts will not occur. go-ssb can't recover if this happens.

**Comment by boreq** [comment]
I think there are two scenarios where this happen:
- first scenario is what we may have fixed and it is a scenario from which the app could recover after a restart
- second scenario which the restarts won't help with
