### ISSUE TITLE
Users blocked by our pubs can still redeem invites to them

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/planetary-ios#545]
This is probably a bug in ssb-server, but I'm opening it here so we can track it.

**Comment by rabble** [comment]
Need to get ssb-server fixed so it doesn't accept an invite from a blocked user.

**Comment by mplorentz** [comment]
ssb-invite issue: https://github.com/ssbc/ssb-invite/issues/29

**Comment by mplorentz** [comment]
This has been patched and deployed to all our pubs.
