### ISSUE TITLE
Refactor post truncation code

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/planetary-ios#579]
The code responsible for truncating post text and adding a "See more" button has several problems. 
- It is extremely slow and negatively impacts scrolling performance. 
- It breaks markdown links sometimes #388
- It breaks after scrolling sometimes #288 
- The text is sometimes not truncated and overflows the cell bounds https://planetary-app.slack.com/archives/CM4EPK324/p1653266311000739

We need to fix, simplify, and optimize this code. One idea is to just using UILabel's `numberOfLines` property and layer the `See More` button on top of the label, rather than trying to embed it with `NSAttributedString`.

**Comment by rabble** [comment]
This will be fixed when we move to SwiftUI #744
