### ISSUE TITLE
App launch is very slow on release/1.2.0

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/planetary-ios#581]
Planetary spends much more time on the splash screen on release/1.2.0 than it does on our production build. Go-ssb seems to be waiting on some indexing during this time, printing messages like:
```
ts="2022-05-23 18:49:57.4256110 (UTC)" level=info index=timestamps event=index-progress done=36.4835283605646 time-left=12s
ts="2022-05-23 18:50:03.8952250 (UTC)" level=debug event=update-replicate feed-want-count=7450 hops=1 took=9.841863875s
ts="2022-05-23 18:50:04.4346430 (UTC)" level=info index=timestamps event=index-progress done=63.83834615131211 time-left=8s
ts="2022-05-23 18:50:11.4342960 (UTC)" level=info index=timestamps event=index-progress done=89.21446480959582 time-left=3s

**Comment by rabble** [comment]
Commenting out this line in api-ios.go makes this delay go away.

sbot.WaitUntilIndexesAreSynced()

But we need to know WHAT this code is doing and why, if commenting out breaks things.

**Comment by mplorentz** [comment]
I did some testing with `sbot.WaitUntilIndexesAreSynced()` and things seem to work ok for me. I'm going to open a PR with this change so we can test it on TestFlight.

**Comment by boreq** [comment]
> I did some testing with `sbot.WaitUntilIndexesAreSynced()` and things seem to work ok for me. I'm going to open a PR with this change so we can test it on TestFlight.

I am analyzing what, if anything, could break because of this.

**Comment by mplorentz** [comment]
@boreq reported in Slack that he doesn't see any obvious issues this would cause. I also didn't see any issues with it after using it over the weekend, so I'm closing this ticket as complete.
