### ISSUE TITLE
Publishing takes too long

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/planetary-ios#583]
This might be caused by #548. We probably need to have a more advanced algorithm to prevent `statistics()` calls from blocking `publish()` calls.

**Comment by mplorentz** [comment]
This is still too slow. Reopening.

**Comment by mplorentz** [comment]
Might be caused by the same issue as #340.

**Comment by rabble** [comment]
let's look at this after we switch to #scuttlego.

**Comment by rabble** [comment]
This has mostly gone away.
