### ISSUE TITLE
"logout and onboard" option copies number of published messages from previous profile

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/planetary-ios#611]
Steps to reproduce:
1. Start on a profile with more than 10 publishes messages
2. Go into the debug settings and choose "logout and onboard"
3. Set up your new profile
4. Try to publish two posts
Expected: both are published
Actual: the first is published and the second gets an error about forked feed protection

**Comment by wsarles** [comment]
I was able to reproduce this nearly 100% of the time with: 

- Start on a profile at least two published messages. 
- Go into the debug settings and choose "logout and onboard"
- Set up your new profile
- Immediately open side menu
- Try to publish a post
- Expected: a post is published
- Actual:  an error about forked feed protection


[PR created](https://github.com/planetary-social/planetary-ios/pull/926)

**Comment by rabble** [comment]
Done, just didn't pass due to intermittent github errors. @martindsq will take a look.

**Comment by mplorentz** [comment]
So glad this is fixed. It will really help with debugging.
