### ISSUE TITLE
Creating new profiles triggers forked feed protection

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/planetary-ios#618]
Steps to reproduce:
1. Start on a profile that has published more than 5 messages
2. Go into the debug settings and choose "Logout and Onboard"
3. Go through onboarding for the new account
4. Try to post
Expected: Posting succeeds
Actual: An error message is displayed that Planetary is restoring

It looks like the `AppConfiguration.numberOfPublishedMessages` is getting copied from the first profile to the second.

**Comment by rabble** [comment]
not for me.

**Comment by mplorentz** [comment]
Duplicate of #611 (thanks @wsarles)
