### ISSUE TITLE
normalize case and diacritics in hashtags

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/planetary-ios#623]
Planetary currently doesn't allow diacritics in hashtags. We should allow them and perhaps normalize them so that, for example, Ahau and #Āhau resolve to the same hashtag? It's a tricky balance between supporting users who don't know how to make diacritics one their keyboards and those who do. Some discussion about this here: `%ZZFT3T8rnWcd6tCqAX3ME5+lHWjpQYAcoWasdbCdhfw=.sha256`.

At the moment #ShowMeYourCoffee isn't the same hashtag as #showmeyourcoffee which is kind of dumb. We should update our sql lookup for hashtags to make sure that the match is case insenstive.

**Comment by rabble** [comment]
Dupe to  #779
