### ISSUE TITLE
Prioritize blob downloads

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/planetary-ios#627]
Currently blobs take way too long to load in Planetary. The experience is especially poor for new users because they have so many blobs to fetch. New users won't see any images load for a long time.

One reason for this is that go-ssb seems to prioritize downloading messages over blobs. This seems like a reasonable choice but really impacts the new user experience, so maybe making sure some blobs are downloaded even during initial sync would be a good idea.

Another reason is that the Swift layer requests all blobs at once. This means that blobs from 6 months ago get downloaded with the same priority as the blobs at the top of the user's Discover feed. We could prioritize the blobs the user is actually looking at by only requesting the ones that are actually on screen or about to be on screen. This would negatively impact offline use though.

We could also try to build some kind of prioritization system in go-ssb, by having a high priority list of blobs we want (for things the user is looking at) and a low priority list (downloading in the background for offline use).

**Comment by mplorentz** [comment]
#230 and #563 would also help with this issue.

**Comment by martindsq** [comment]
its better now but we will fix it better in scuttlego.
