### ISSUE TITLE
Fix "database still open" error on start

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/planetary-ios#632]
@rabble's Mac install of Planetary got into a state where Planetary couldn't start because the database was still open. We can probably catch this error in `GoBot.login()` and recover by callout `logout()`. [logs](https://github.com/planetary-social/planetary-ios/files/8900514/com.planetary.ios.2022-06-13--19-57-37-296.log)

**Comment by rabble** [comment]
we think it's fixed.
