### ISSUE TITLE
Network/energy usage is too high

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/planetary-ios#640]
Planetary 1.2.0's energy usage is always "Very High" even when we aren't really syncing or verifying new messages. It looks like we are doing a lot of disk reads and outbound network transmission even when the app is idle. Let's find what part of the code is doing this and fix it so we don't waste our user's bandwidth and battery.

**Comment by rabble** [comment]
On going issue, might not fix and just switch to scuttlego.

**Comment by rabble** [comment]
This is still an issue and causing problems. 

@wsarles will look in to with instruments

**Comment by wsarles** [comment]
My research with Instruments revealed that increased energy use of the app is directly correlated to network requests performed by GoSSB. There are two instances in which network requests are at an elevated level:

1) An established user restoring their identity.
2) A user scrolling the discovery feed for > 2 minutes. 

After discussing with @martindsq, we decided to wait and see if scuttlego will ease energy use.

**Comment by boreq** [comment]
With the latest changes we are in the yellow zone (high) but at the bottom of it and 80-85% of "component utilization" is related to "overhead" which is probably just running the radios etc as we stay connected to peers at all times.

**Comment by boreq** [comment]
![Image](https://user-images.githubusercontent.com/1935975/222264713-043450a2-caa6-44de-b4d1-e7f80bd8a17b.png)

**Comment by boreq** [comment]
I think after #1255 is closed we should decide if we can close this ticker about network+energy usage and just replace it with one about specifically network usage.

**Comment by mplorentz** [comment]
Scuttlego is already much better than go-ssb. I support closing this, although certainly there are further optimizations that could be done we probably have solved the "I don't use Planetary because my phone gets hot and it kills my battery" and are more in the territory of other network-intensive apps.
