### ISSUE TITLE
Add sections to the document explaining topics that Matt asked about

### ISSUE THREAD

**Issue by boreq** [planetary-social/planetary-ios#644]
https://docs.google.com/document/d/1KVmPXGH1zeD4lWGPW6kXSWPdETMlSqxRH_JIZBvwlIQ

**Comment by mplorentz** [comment]
@boreq I think you started on this already. Is it done?

**Comment by boreq** [comment]
I added a section about the persistence layer. I think the other question was about the connection manager - would you like me to write more about that topic as well?

**Comment by mplorentz** [comment]
Not unless you want to. It would obviously be nice to document the connection manager at some point, but I don't think it needs to be in that doc necessarily.
