### ISSUE TITLE
User Directory has no search function during Onboarding

### ISSUE THREAD

**Issue by knowtheory** [planetary-social/planetary-ios#66]
Hey!  I'm super interested in how Planetary comes together.  I signed up for the iOS beta here, and was a bit confused at the user directory listing during the onboarding process.  The listing doesn't have a search bar or any other way to filter the list, so it just requires manually scrolling through to try and identify anybody I know.  I noticed that the user directory once you're past onboarding does have a search bar.

**Comment by amandabee** [comment]
Ahh, that's not a great experience! 

We should definitely add a search to the user directory that new users see.

**Comment by knowtheory** [comment]
Here's a screenshot of what it looks like

![9CE0B3AD-2BD7-4787-9BEB-C09856C2F404_1_102_o](https://user-images.githubusercontent.com/192/79135605-79affe00-7d64-11ea-9bcb-0c1adf3e0236.jpeg)

Also!  I don't know most of these people!

**Comment by amandabee** [comment]
Two issues: we need to add search, and change the language on that page.
