### ISSUE TITLE
View Source on Messages

### ISSUE THREAD

**Issue by rabble** [planetary-social/planetary-ios#662]
In order to communicate the open nature of secure scuttlebutt we need to allow users to view source for messages. 

Ideally we'd do some nifty color rendering of the message format with a link to the docs for more information about the message type and system. 

This needs design first. 

<img width="519" alt="Screen Shot 2022-06-24 at 11 31 09 AM" src="https://user-images.githubusercontent.com/76/175568320-5808a3b1-4ad1-4b6a-8d14-26679b3ac783.png">

**Comment by boreq** [comment]
Let users select/copy text, maybe one line of text which explains that this is what your message looks like when it travels between devices, probably popup?
