### ISSUE TITLE
Onboarding: Have to post before you see any messages

### ISSUE THREAD

**Issue by amandabee** [planetary-social/planetary-ios#67]
From a user: "I wasn't able to see anything until I posted something and then everything appeared even though I followed people." 

I suspect that what's really happening here is that there needs to be a refresh to pull in others posts, but we should either a) do that refresh when you move to the next stage in onboarding or b) tell you how to refresh.

**Comment by mplorentz** [comment]
This should be solved in #454, which is in progress. I'm going to close this ticket as a dupe.
