### ISSUE TITLE
Updated Profile Page

### ISSUE THREAD

**Issue by rabble** [planetary-social/planetary-ios#681]
This ticket is for the design work for #680 

@Chardot can come up with a change of the layout for the profile page to be able to either see the content they posted or the scuttleverse from their vantage point. 

- [ ] Display a list of who the user has blocked
- [ ] Display a feed of content from the perspective of that user. 
- [ ] Mutuals when listing following / followers / blocks
- [ ] Display a list of all the reactions by the user (what did they like)

If the profile is a pub, then the default should be to display the feed from their perspective, who do they follow. If the profile is not a pub, then first we see everything they have posted, with the ability to switch to see what they follow.

#### Social Relationships

When looking at a profile, i want to know, how do i relate to this person. In order to do that we need to display a few things. 

* Blocks - Which of the people you follow block somebody, vs others you know about. 
* Follows - This person follows x people who you follow / follow you
* Followed by - Who do you follow / are followed by that this person is also followed by.

These are critical things for users to decide, is this somebody i want to follow.

**Comment by Chardot** [comment]
This is the current state of the Profile design. I'm still applying changes based on feedback:

![Image](https://user-images.githubusercontent.com/477835/183500132-d92adc05-ec47-4a90-b950-a2d4a938e900.png)

**Comment by Chardot** [comment]
The following are the [designs](https://www.figma.com/file/6oTsbY3vHME19RNtgSGdAw/Planetary-Design-Plan?node-id=2203%3A28987) for a user and server profile screens including all the features listed in this issue.

![Image](https://user-images.githubusercontent.com/477835/189201942-fdc6c921-6a47-481b-808e-de8464af1f3d.png)

I understand at the moment we can't implement all the different tabs at once, so this will probably start with a refresh of the upper section of the screen and the two main tabs at the bottom: Posts and Feed, and we'll leave Interactions and Network for a future iteration.

**Comment by Chardot** [comment]
@martindsq Let me know if you want to meet to analyze these screens before implementation.

**Comment by mplorentz** [comment]
@Chardot I'm not @martindsq but if I were implementing this I would like to see some other states:
- An empty profile that we have no data for
- A blocked profile
- A loading state

**Comment by Chardot** [comment]
Progress on Profile screen design: https://www.figma.com/file/6oTsbY3vHME19RNtgSGdAw/Planetary-Design-Plan?node-id=1998%3A26305

**Comment by rabble** [comment]
Design is parallel to the web viewer design. 

Going to try combining feed from uikit with the swiftui profile redesign
