### ISSUE TITLE
Check for go-ssb being stuck while the app is in the background and restart

### ISSUE THREAD

**Issue by rabble** [planetary-social/planetary-ios#727]
Sometimes go-ssb gets stuck and won't sync new content until it's killed and restarted. We can tell when it's timing out, but not restart it when it's stuck like that. So when the app notices the timeouts have been hit in swift, and the app is NOT in the foreground, we should force quit the app, so the next time the user opens it or apple spins it up in the background then go-ssb will start syncing again.

**Comment by martindsq** [comment]
If this happens in the background call crash in swift.

**Comment by boreq** [comment]
Let's see what is happening on the EBT branch and reevaluate after a week. For now lets just wait.
