### ISSUE TITLE
Optimize patchwork algorithm and make it the default

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/planetary-ios#728]
We can make the patchwork algorithm much faster by adding a `last_reply` column that is updated when we update the tangles ticket. Let's do that and make the patchwork algorithm the default.

**Comment by mplorentz** [comment]
This is slow for me again. Like it's taking 15 seconds to load the home feed. I think maybe when I optimized it the first time my SQLite database had some extra indexes from debugging that others didn't have. Since resyncing my feed it has been very slow. I'm taking another look at this.

**Comment by rabble** [comment]
Merged
