### ISSUE TITLE
Planetary 'contact' messages behave in a nonstandard way, causing them to be rendered in various incorrect ways in other clients.

### ISSUE THREAD

**Issue by Powersource** [planetary-social/planetary-ios#73]
See https://gitlab.com/staltz/manyverse/-/issues/837 for more info.

**Comment by cryptix** [comment]
Hey @Powersource, i just cloned what patchwork does as far as I know. I read the manyverse issue but i still don't know what's _wrong_ about them?

**Comment by Powersource** [comment]
Example patchwork unfollow

```json
{
  "key": "%GibYTGcX9koBLf/WlhAAj1IbtQqf66XkgShxE8lXdZk=.sha256",
  "value": {
    "previous": "%0GLHNABglginTCfAq2HVzi1a4SI1IL04be8BIgQvWMo=.sha256",
    "sequence": 4811,
    "author": "@Vz6v3xKpzViiTM/GAe+hKkACZSqrErQQZgv4iqQxEn8=.ed25519",
    "timestamp": 1587075389364,
    "hash": "sha256",
    "content": {
      "type": "contact",
      "contact": "@y662fdOwp+YY8hclF37vqfVGjxA43K7FODVNO/drKtE=.ed25519",
      "following": false
    },
    "signature": "JPikGtLjeF2MsZreOaZ7S9lNZ4KSH6AarFu/Kbi+OwFQrRoGMhIIoCxk+SKT/xBb8TXaFrtakaNDJeR5I620AQ==.sig.ed25519"
  },
  "timestamp": 1587075389364.001
}
```

patchwork block

```json
{
  "key": "%lYYofuNHlgzmLUa1kbweBFdx39GsT/cYOXBl29rPiEs=.sha256",
  "value": {
    "previous": "%Gqf0y8kopZLRCFiMngF8Hw9rw+RNi78tWbAuCbopsWg=.sha256",
    "sequence": 4776,
    "author": "@Vz6v3xKpzViiTM/GAe+hKkACZSqrErQQZgv4iqQxEn8=.ed25519",
    "timestamp": 1586038918270,
    "hash": "sha256",
    "content": {
      "type": "contact",
      "contact": "@9BbJwPDjcyIqrOUPNn0nJZBduWdIrpMk3Cjz5MP361s=.ed25519",
      "blocking": true
    },
    "signature": "4IG++V8jTG3NClaXECZyS2JMZ+UV8TuRkxxFM/npHuwCmZ8hgkFmirmrCI4mZUNaeC9IxI5AIyXLN8TDXDWICQ==.sig.ed25519"
  },
  "timestamp": 1586038918272
}
```

If I'm understanding the difference correctly then I think it's this:

* Planetary publishes the entire "state" (`following` and `blocking`).
* Patchwork (and others) only publishes sort of the diff compared to the old state (which is also why we can render them so easily), e.g. if you're  now blocking someone, the message says `blocking: true`, but `following` is undefined.

**Comment by cryptix** [comment]
I see... let me think what I can do about that.

Just to repeat my understanding, go-ssb should omit the unchanged fields.

**Comment by Powersource** [comment]
I think it's pretty much that yeah.

Just curious, how do you render these messages (if you do), do you diff with the earlier state to figure out what the user did?

**Comment by cryptix** [comment]
> I think it's pretty much that yeah.

I see, should be possible with some extra leg-work. Needs custom (un)marshalling in Go but that's my problem.

> Just curious, how do you render these messages (if you do), do you diff with the earlier state to figure out what the user did?

We don't render those message but just the latest state two users have.

**Comment by martindsq** [comment]
@Powersource @cryptix  I'm closing this issue because I don't see this behavior in Planetary anymore. We are sending follow/blocks in the same way Patchwork and manyverse does. Let me know if you think we should re open this.

**Comment by mplorentz** [comment]
Looking at my own feed, I'm still seeing the behavior described in this ticket. Here is me following someone from this week in Planetary:
```
{
  "key": "%MRK0mjaJQfDPjwOjQEld6YGC3SxEqUeXo1nj9B/xyNM=.sha256",
  "value": {
    "previous": "%vXKyo/+gNUaXnh8mZY5VcrkXR2XZIhEcEqZUlw7AsDQ=.sha256",
    "author": "@4wXR/KiJrkz9D2LPXpZl5XOLw+gYCoJW6p6rwFlI5yA=.ed25519",
    "sequence": 388,
    "timestamp": 1653438303530,
    "hash": "sha256",
    "content": {
      "blocking": false,
      "type": "contact",
      "following": true,
      "contact": "@ed1T9mWlMAg2rfMG+r2j1yJaS7UIsZZox5SQFWNDAuc=.ed25519"
    },
    "signature": "sY2FaD5PsTpzCssZOnI+mIpD3bHZLg/Jp/39FIZpAqSEp7ghRrOWg95rgxPJ4REb46inlOX7xhjkwnnEmUCbAw==.sig.ed25519"
  },
  "timestamp": 1653438306541
}
```

But Patchwork generates a follow message like this:
```
{
  "key": "%T/kjiuDf4OXsrXmNdtTP3BDMKe2x7fqGLu/ykn4lrkM=.sha256",
  "value": {
    "previous": "%PWjC2b/dE4xS7tg+AtfR/5xx8PD8SzdXy+hnL0ZYVNA=.sha256",
    "sequence": 1196,
    "author": "@kS1GT34Sg+Kzjcqoehz//afmIQC5+CGo8O/KvMddVrM=.ed25519",
    "timestamp": 1652883343548,
    "hash": "sha256",
    "content": {
      "type": "contact",
      "contact": "@KutKRjsimme+d37Q1kdMnnxC/Hy8zZh9KIwZWkcxxNA=.ed25519",
      "following": true
    },
    "signature": "B20A6+5Vg9mQyNrtODPXTNmKsLp+7PN5wuHKiV6UbPF+hw6Hh1oA5/clSxmzLI8J5bSp1oF8ACorl+NDd1IABg==.sig.ed25519"
  },
  "timestamp": 1652883396187
}
```

So I think Planetary still has this behavior. However it seems like maybe it isn't a problem anymore? It sounds like Manyverse displays these contact messages correctly now, and given that there are thousands of messages like this out in the wild now it seems like future clients will probably want to handle them. So unless we are breaking the spec maybe it's ok to leave this closed?
