### ISSUE TITLE
App badge is not cleared after reading notifications

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/planetary-ios#733]
The app badge is not being cleared for me even after I have read all notifications on the notifications tab. Unfortunately I don't have clear steps to reproduce but this happened to me while resyncing my database.

https://user-images.githubusercontent.com/1165004/179614960-4e368650-1046-4eb1-ac75-d6b415efb43f.MP4

**Comment by martindsq** [comment]
It should be a report somewhere in the list, remember we don't have a different design for unread notifications. I noticed you are pulling down to refresh, do you expect a pull down to refresh to mark all notifications as read?

**Comment by martindsq** [comment]
Closing this as #735 should have fixed this
