### ISSUE TITLE
Reports queries can stack up and make the db slow

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/planetary-ios#734]
I've noticed that a lot of queries (especially the ones we make for follow message cells) are slower since we started keeping track of the read status of messages in #725. I haven't done a full diagnosis but I think there are two things from that PR keeping the database much busier in general: 
- Many NumberOfReportsOperations can end up running at once. This can happen because every time a new report is created a new operation is forced to start. If many reports are created at once these operations back up. The operations are also started after every refresh, which is roughly every 5 seconds. These are supposed to be rate limited to one every 60 seconds but the code only checks when the last request completed, so if queries get backed up this contributes to the problem getting worse.
- The `markMessageAsRead` function also be contributing to the slowdowns. It has to read from a lot of tables and construct Report and Post objects in memory before it can mark the Report as read. This function can be called many times per second if the user scrolls through a lot of posts. We could optimize this process, perhaps by checking if a message is already marked read before making the expensive queries.

The best way to reproduce these issues is probably either to 1) do a full resync on a profile with thousands of messages or 2) do a lot of scrolling on the home feed and notifications tabs on a profile with a lot of notifications.

**Comment by martindsq** [comment]
Closing this as #739 should have fixed this
