### ISSUE TITLE
Profile picture aspect ratio is wrong

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/planetary-ios#753]
This user's profile picture is getting squished. It doesn't look like this anywhere but on the profile page header. Seems like we aren't setting the aspect ratio correctly.

![Image](https://user-images.githubusercontent.com/1165004/180851596-89abb0cb-e391-498a-8560-f395c6e48fd0.jpg)

**Comment by rabble** [comment]
It's only on post cell, not on the full profile view.

**Comment by mplorentz** [comment]
You can also see this on identity `@+u1vX9VamcbSmLMAW3jAyN3M0JIvNrerOzQ9X8KwlR4=.ed25519`.
