### ISSUE TITLE
Add icons to Chinese and french language pubs

### ISSUE THREAD

**Issue by rabble** [planetary-social/planetary-ios#756]
Get Jeremey List to translate text... get @chardot to design logo, add to planetary.

**Comment by Chardot** [comment]
Here are the icons:

![Pubs - Chinese](https://user-images.githubusercontent.com/477835/181820787-f91fa5ef-5c04-4c57-8b7a-59f68f7e9e14.png)

![Pubs - French](https://user-images.githubusercontent.com/477835/181820793-5ffb7949-06dd-4241-9a5c-b523440aa277.png)
