### ISSUE TITLE
Random Feed Algorithm

### ISSUE THREAD

**Issue by rabble** [planetary-social/planetary-ios#759]
There's lots of old interesting content in ssb. When a user installs an app, they're only going to get a few new posts a day, at best. But there is tons of old interesting content. 

So i was thinking, we could have a feed algorithm which was 'random old shit i haven't seen'. We can do this because we've got the viewed flag now for content. 

Initially, we can just add it as one of the choices in the select an algorithm settings, but in the future i think it'd be cool to have some button you could press to trigger it. Show me random shit. ;-D I'm sure @Chardot could come up with a design, it can be a kind of game play dynamic. 

- [ ] Update text for help drawer about how the discover algorithm works.

**Comment by mplorentz** [comment]
Here's a post about how to do this in SQLite. Seems pretty easy
https://stackoverflow.com/a/24591696

Although our feed strategies currently contain a ton of duplicate code. It's already caused a a couple bugs so probably before we add the next one we should refactor them to share more.

**Comment by rabble** [comment]
Update text to the help text to explain the algorithm, so it's not chrono.

**Comment by boreq** [comment]
It is my understanding that it is done.
