### ISSUE TITLE
App is hanging w/ a Loading new messages dialog

### ISSUE THREAD

**Issue by knowtheory** [planetary-social/planetary-ios#76]
Rabble replied to one of my posts last week, and I wanted to respond, but the app popped up a "Loading new messages" spinner dialog, and just sits that way.  None of the buttons do anything while the dialog is up (so i can't really use the app right now).

**Comment by rabble** [comment]
That's terrible. Kill the app and load again. You could help us by going in to settings > Advanced settings > Dangerous and powerful debug menu > download logs.

**Comment by bartsipes** [comment]
I get this behavior almost every time I open the app. I can't even get to the settings menu to attempt to download the logs

**Comment by mplorentz** [comment]
This should be fixed now. Please reopen if you see it again!
