### ISSUE TITLE
Prompt for App Store reviews

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/planetary-ios#787]
Apple gives us a way to prompt for users to leave us a rating on the App Store. This would be a good thing to do as a strong rating encourages people to download.

Some care should be taken not to interrupt users while they are in the middle of a task. Also we should avoid prompting new users who may not be used to the app yet. Maybe a good heuristic would be to show the prompt after publishing a post if they have more than 100 published messages (including follows, likes, etc.). Apple ensures that the prompt is not shown more than 3 times per year, but perhaps we should show it even less, like 1 time a year.

**Comment by samuelkubinsky** [comment]
Hey, I would like to take a look at this :)

**Comment by mplorentz** [comment]
@samuelkubinsky go for it!

**Comment by mplorentz** [comment]
Done by @samuelkubinsky in #942.
