### ISSUE TITLE
Region should not be used for selecting the app language

### ISSUE THREAD

**Issue by boreq** [planetary-social/planetary-ios#796]
My system language is set to English and region is set to Poland. When running the simulator I have the region and language set to default to the system settings. Despite this the language which shows up in the app is Polish. I believe this is because we incorrectly use the region instead of the language to select the language in our app.

**Comment by danlatorre** [comment]
Is this still to do? Important to respect users' sys prefs.

**Comment by mplorentz** [comment]
@danlatorre yeah, still todo.

**Comment by martindsq** [comment]
@boreq this should be fixed in main after I merged #1125. I tested it in a simulator and it worked as expected. Bother to test again and close this issue?

**Comment by boreq** [comment]
Given that my simulator no longer speaks polish to me even though my system language is set to english I think this is indeed fixed.
