### ISSUE TITLE
Add bio step back to onboarding flow

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/planetary-ios#805]
Steps to reproduce:
1. Install Planetary 1.2.6 from the App Store on an iOS 15.6 device (observed on iPhone 12 mini and iPhone 13 Pro but did not happen on iPhone SE)
2. Go through onboarding, make sure to set a name
3. On the bio step, type something in the box and press next
Expected: you are taken to the next screen
Actual: the app freezes

**Comment by mplorentz** [comment]
Temporary fix in #804

**Comment by Chardot** [comment]
Probably rewriting this flow in SwiftUI?
