### ISSUE TITLE
Planetary is not replicating profiles 2 hops away

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/planetary-ios#826]
Steps to reproduce:
1. Do a fresh install of Planetary (observed on 1.3.3, 1.3.2, 1.2.7)
2. Go through onboarding.
3. Follow someone from the directory tab who is following more than 0 people and is followed by the Planetary pubs
4. Wait for replication to happen
Expected: The feeds of the accounts 1 hop away from the person you followed are downloaded and displayed on the discover tab.
Actual: Only the feed of the person you followed is downloaded, even after waiting a long time and restarting the app several times.

**Comment by boreq** [comment]
This is related to code that exists in go-ssb.

https://github.com/ssbc/go-ssb/blob/8bb04d96e053f4d00b8d9f6cadfeb5cbd9b87756/graph/builder.go#L459-L465

**Comment by boreq** [comment]
I guess fixed in 1.3.3.
