### ISSUE TITLE
sometimes ebt branch doesn't update... rabble's install

### ISSUE THREAD

**Issue by rabble** [planetary-social/planetary-ios#836]
Doesn't seem to update the db with new messages...

[com.planetary.ios 2022-09-12--03-25-21-133.log](https://github.com/planetary-social/planetary-ios/files/9551157/com.planetary.ios.2022-09-12--03-25-21-133.log)
[gobot-2022-09-12_04-52.log](https://github.com/planetary-social/planetary-ios/files/9551159/gobot-2022-09-12_04-52.log)

**Comment by mplorentz** [comment]
go-ssb wont fix
