### ISSUE TITLE
Follows from accounts with no about message are not displayed on the Notifications tab

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/planetary-ios#840]
Steps to reproduce:
1. Create a new account and do not set a name.
2. Follow another Planetary user with this account.
3. Switch to the the other Planetary user's device and wait for notification to be displayed "Somebody started following you"
4. Open the notification tab

Expected: The notification that "Somebody started following you" is displayed, and you can tap on it to see who it is.
Actual: The notification is not displayed. The new message bubble is displayed, but tapping on it does not help.

**Comment by wsarles** [comment]
This looks to be fixed in d5aeff0b

![Untitled-1](https://user-images.githubusercontent.com/1332769/197547214-962a151c-8ac3-48d4-b7d9-24c59c72f1e0.png)
