### ISSUE TITLE
Draft is not cleared after posting

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/planetary-ios#868]
Sometimes your last post or reply is still displayed in the text box after you have already posted it. This is happening because the draft post is not being properly cleared after publishing it.

**Comment by mplorentz** [comment]
This just happened to me again on 1.3.5 (375). Should have been fixed in #869.

**Comment by wsarles** [comment]
Unfortunately, I ran into this same issue today. 
![Old post text showing up in new post editor mov](https://user-images.githubusercontent.com/1332769/196305764-70ffe11c-5082-4780-b5e5-69271766eed0.gif)

**Comment by martindsq** [comment]
Closed this as [completed](https://github.com/planetary-social/planetary-ios/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3Acompleted) in https://github.com/planetary-social/planetary-ios/pull/1261

**Comment by mplorentz** [comment]
@martindsq bless you for fixing this. Obviously I was having a hard time 😅
