### ISSUE TITLE
Fix CSRF Error on Planetary.name

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/planetary-ios#886]
Steps to reproduce:
1. Launch Planetary from a device that hasn't joined the Planetary.name room yet.
2. Navigate to Settings -> Aliases -> Register new Alias
3. Tap "Join Planetary.name room"
Expected: the room is joined successfully
Actual: an error message is displayed

The underlying error message from the server is "CSRF token invalid".

**Comment by mplorentz** [comment]
Maybe we need to initialize a cookie store for this flow. But also maybe this is a bug in the server code because I thought CSRF cookies should only be set if you are signed in, and you don't have to be signed in for invitation redemption.

**Comment by mplorentz** [comment]
Also maybe this is an error added to ssbc/go-ssb-room between when we added the magic token thing and the HEAD of master on planetary-social/go-ssb-room

**Comment by boreq** [comment]
This is not the case anymore. We suspect that an older version of the room code may have been incorrectly deployed.
