### ISSUE TITLE
Cannot redeem room invitation from cold boot

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/planetary-ios#895]
Steps to reproduce:
1. Force kill Planetary so it is not launched
2. Open an http room invitation link in your browser
3. Tap the button to open the invitation in Planetary
Expected: the invitation is redeemed successfully
Actual: the invitation is not redeemed

**Comment by wsarles** [comment]
In review.

**Comment by wsarles** [comment]
Merged.
