### ISSUE TITLE
Publish announce messages for room aliases

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/planetary-ios#899]
When the user joined a room server we should publish an announcement message on their ssb feed so other clients can display the alias.

The message should look like this:

```
{
  "key": "%5Jha6TzQyaIg+7WYI+e/bDVaVrMDik5kawvNT19eFsA=.sha256",
  "value": {
    "previous": "%8jW4BHWc6xo0H89R59cwap2Dwy2klAn9ZKcNV9knKy8=.sha256",
    "sequence": 22,
    "author": "@4RzUEMr+dGtLVubYdU4LK/DOjYpjy0EaDUi06Wgk7io=.ed25519",
    "timestamp": 1643822257167,
    "hash": "sha256",
    "content": {
      "type": "room/alias",
      "action": "registered",
      "alias": "matt",
      "room": "@uMYDVPuEKftL4SzpRGVyQxLdyPkOiX7njit7+qT/7IQ=.ed25519",
      "aliasURL": "https://matt.hermies.club"
    },
    "signature": "PAWcnkfIyOIFDWrRV7OaB0WDHXAIHiU2X8xbdyvvUtV+gFv0h+lW8rO40YoQNlgQRPqday+RXQr3JHTm2TDYAg==.sig.ed25519"
  },
  "timestamp": 1643822257172
}
```

**Comment by rabble** [comment]
90% complete, just one failing test.

**Comment by wsarles** [comment]
[In review.](https://github.com/planetary-social/planetary-ios/pull/1005)

**Comment by wsarles** [comment]
merged

**Comment by mplorentz** [comment]
I think there is one more task to do here. From my [comment here](https://github.com/planetary-social/planetary-ios/pull/1005#pullrequestreview-1216247681):
> I think we are missing one component which is publishing an announcement ourselves when we register an alias successfully from within Planetary. This should probably be a call to publish somewhere in the GoBot.register(alias: String, in: Room) function. If you'd like we could merge this PR without that part and you could do it in a separate PR.
