### ISSUE TITLE
Add choosing room and setting alias to onboarding 

### ISSUE THREAD

**Issue by rabble** [planetary-social/planetary-ios#940]
We need to have a list of rooms we know about and let users choose. Join a room and set a name and see what their url / name is.

**Comment by Chardot** [comment]
I had a call with @wsarles where we discussed the requirements for this flow, and this is my design proposal:

![Screenshot 2022-11-01 at 19 28 20](https://user-images.githubusercontent.com/477835/199310258-acc54fc4-7e4a-496e-bedf-bc349501b3b0.png)

[Link to designs on Figma](https://www.figma.com/file/6oTsbY3vHME19RNtgSGdAw/Planetary-Design-Plan?node-id=3178%3A28149)

I chose not to call these «Rooms» to avoid users misinterpreting this as private spaces where they'll be able to post stuff that is not visible to the wider network.

@rabble what do you think?

**Comment by Chardot** [comment]
@rabble just confirmed that aliases are not permanent and can be changed, so I updated the copy under the text input:

![Screenshot 2022-11-01 at 19 58 36](https://user-images.githubusercontent.com/477835/199316150-ffb50cce-70a3-4033-be18-d86f6b6bf994.png)

**Comment by Chardot** [comment]
Also this is a preview of the same screens in light mode

![Screenshot 2022-11-03 at 19 06 56](https://user-images.githubusercontent.com/477835/200391284-f488f594-1384-404e-87cb-7ec72e4b93ef.png)

**Comment by wsarles** [comment]
UI has been implemented in SwiftUI.. currently hooking it up.

**Comment by wsarles** [comment]
[In review.](https://github.com/planetary-social/planetary-ios/pull/967)

**Comment by wsarles** [comment]
Merged.
