### ISSUE TITLE
Joining Planetary.name room says "Oops! Invitation redeemed!"

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/planetary-ios#949]
Steps to reproduce:
1. Launch Planetary on a device that hasn't already joined the Planetary.name room (or delete it from the list of rooms if it has already been joined)
2. Navigate to Settings -> Manage Aliases -> Register New Alias
3. Tap "Join Planetary.name"

Expected: A message like "Success! Invitation redeemed" is displayed.
Actual: The message "Oops! Invitation redeemed" is displayed.

<img src="https://user-images.githubusercontent.com/1165004/200654788-ef4ffdd5-8b37-4d98-96d4-88872139dddc.png" width="300" />

[video](https://user-images.githubusercontent.com/1165004/200654824-e1469c1b-356e-4496-a4a9-59abc0baa128.mp4)

**Comment by mplorentz** [comment]
It should probably be in TODO, but I was going to let ya'll prioritize it in sprint planning.

**Comment by boreq** [comment]
Probably no status then?

**Comment by mplorentz** [comment]
@boreq yes. I didn't know how to put things in the "No status" column if you didn't create them on the sprint board. But I see now you can remove it from the project and re-add it and it will go there, so I did that.

**Comment by wsarles** [comment]
[In review](https://github.com/planetary-social/planetary-ios/pull/1039)
