### ISSUE TITLE
scuttlego: the new message pill doesn't show up

### ISSUE THREAD

**Issue by boreq** [planetary-social/planetary-ios#986]
The pill only shows up for Rabble's own actions.

**Comment by mplorentz** [comment]
This is working for me now on `scuttego-migration-ui`. I think maybe it actually broke on `main` and was fixed in https://github.com/planetary-social/planetary-ios/pull/1086.

**Comment by martindsq** [comment]
Closing it because it was broken on main but fixed in #1086
